// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_log.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const countActivityBySquad = `-- name: CountActivityBySquad :one
SELECT count(*) FROM activity_log
WHERE squad_id = $1
  AND ($2::activity_actor_type IS NULL
       OR actor_type = $2)
  AND ($3::TEXT IS NULL
       OR entity_type = $3)
  AND ($4::TEXT IS NULL
       OR action = $4)
`

type CountActivityBySquadParams struct {
	SquadID          uuid.UUID             `json:"squad_id"`
	FilterActorType  NullActivityActorType `json:"filter_actor_type"`
	FilterEntityType sql.NullString        `json:"filter_entity_type"`
	FilterAction     sql.NullString        `json:"filter_action"`
}

func (q *Queries) CountActivityBySquad(ctx context.Context, arg CountActivityBySquadParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivityBySquad,
		arg.SquadID,
		arg.FilterActorType,
		arg.FilterEntityType,
		arg.FilterAction,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertActivityEntry = `-- name: InsertActivityEntry :one
INSERT INTO activity_log (
    squad_id, actor_type, actor_id, action, entity_type, entity_id, metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, squad_id, actor_type, actor_id, action, entity_type, entity_id, metadata, created_at
`

type InsertActivityEntryParams struct {
	SquadID    uuid.UUID         `json:"squad_id"`
	ActorType  ActivityActorType `json:"actor_type"`
	ActorID    uuid.UUID         `json:"actor_id"`
	Action     string            `json:"action"`
	EntityType string            `json:"entity_type"`
	EntityID   uuid.UUID         `json:"entity_id"`
	Metadata   json.RawMessage   `json:"metadata"`
}

func (q *Queries) InsertActivityEntry(ctx context.Context, arg InsertActivityEntryParams) (ActivityLog, error) {
	row := q.db.QueryRowContext(ctx, insertActivityEntry,
		arg.SquadID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.ActorType,
		&i.ActorID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listActivityBySquad = `-- name: ListActivityBySquad :many
SELECT id, squad_id, actor_type, actor_id, action, entity_type, entity_id, metadata, created_at FROM activity_log
WHERE squad_id = $1
  AND ($2::activity_actor_type IS NULL
       OR actor_type = $2)
  AND ($3::TEXT IS NULL
       OR entity_type = $3)
  AND ($4::TEXT IS NULL
       OR action = $4)
ORDER BY created_at DESC
LIMIT  $6
OFFSET $5
`

type ListActivityBySquadParams struct {
	SquadID          uuid.UUID             `json:"squad_id"`
	FilterActorType  NullActivityActorType `json:"filter_actor_type"`
	FilterEntityType sql.NullString        `json:"filter_entity_type"`
	FilterAction     sql.NullString        `json:"filter_action"`
	PageOffset       int32                 `json:"page_offset"`
	PageLimit        int32                 `json:"page_limit"`
}

func (q *Queries) ListActivityBySquad(ctx context.Context, arg ListActivityBySquadParams) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, listActivityBySquad,
		arg.SquadID,
		arg.FilterActorType,
		arg.FilterEntityType,
		arg.FilterAction,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
