// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countAgentsBySquad = `-- name: CountAgentsBySquad :one

SELECT COUNT(*) FROM agents
WHERE squad_id = $1
  AND status != 'terminated'
`

// NOTE: CheckCycleInHierarchy uses a recursive CTE which sqlc cannot parse.
// It is implemented as a raw SQL query in the repository layer. The query is:
//
// WITH RECURSIVE ancestors AS (
//
//	SELECT id, parent_agent_id, 1 AS depth
//	FROM agents WHERE id = $1
//	UNION ALL
//	SELECT a.id, a.parent_agent_id, anc.depth + 1
//	FROM agents a JOIN ancestors anc ON a.id = anc.parent_agent_id
//	WHERE anc.depth < 10
//
// )
// SELECT EXISTS (SELECT 1 FROM ancestors WHERE id = $2) AS would_cycle;
func (q *Queries) CountAgentsBySquad(ctx context.Context, squadID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgentsBySquad, squadID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (
    squad_id, name, short_name, role, status,
    parent_agent_id, adapter_type, adapter_config,
    system_prompt, model, budget_monthly_cents
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11
)
RETURNING id, squad_id, name, short_name, role, status, parent_agent_id, adapter_type, adapter_config, system_prompt, model, budget_monthly_cents, created_at, updated_at
`

type CreateAgentParams struct {
	SquadID            uuid.UUID             `json:"squad_id"`
	Name               string                `json:"name"`
	ShortName          string                `json:"short_name"`
	Role               AgentRole             `json:"role"`
	Status             AgentStatus           `json:"status"`
	ParentAgentID      uuid.NullUUID         `json:"parent_agent_id"`
	AdapterType        NullAdapterType       `json:"adapter_type"`
	AdapterConfig      pqtype.NullRawMessage `json:"adapter_config"`
	SystemPrompt       sql.NullString        `json:"system_prompt"`
	Model              sql.NullString        `json:"model"`
	BudgetMonthlyCents sql.NullInt64         `json:"budget_monthly_cents"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgent,
		arg.SquadID,
		arg.Name,
		arg.ShortName,
		arg.Role,
		arg.Status,
		arg.ParentAgentID,
		arg.AdapterType,
		arg.AdapterConfig,
		arg.SystemPrompt,
		arg.Model,
		arg.BudgetMonthlyCents,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Name,
		&i.ShortName,
		&i.Role,
		&i.Status,
		&i.ParentAgentID,
		&i.AdapterType,
		&i.AdapterConfig,
		&i.SystemPrompt,
		&i.Model,
		&i.BudgetMonthlyCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, squad_id, name, short_name, role, status, parent_agent_id, adapter_type, adapter_config, system_prompt, model, budget_monthly_cents, created_at, updated_at FROM agents
WHERE id = $1
`

func (q *Queries) GetAgentByID(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Name,
		&i.ShortName,
		&i.Role,
		&i.Status,
		&i.ParentAgentID,
		&i.AdapterType,
		&i.AdapterConfig,
		&i.SystemPrompt,
		&i.Model,
		&i.BudgetMonthlyCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentParent = `-- name: GetAgentParent :one
SELECT id, squad_id, role FROM agents
WHERE id = $1
`

type GetAgentParentRow struct {
	ID      uuid.UUID `json:"id"`
	SquadID uuid.UUID `json:"squad_id"`
	Role    AgentRole `json:"role"`
}

func (q *Queries) GetAgentParent(ctx context.Context, id uuid.UUID) (GetAgentParentRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentParent, id)
	var i GetAgentParentRow
	err := row.Scan(&i.ID, &i.SquadID, &i.Role)
	return i, err
}

const getSquadCaptain = `-- name: GetSquadCaptain :one
SELECT id, squad_id, name, short_name, role, status, parent_agent_id, adapter_type, adapter_config, system_prompt, model, budget_monthly_cents, created_at, updated_at FROM agents
WHERE squad_id = $1
  AND role = 'captain'
  AND status != 'terminated'
LIMIT 1
`

func (q *Queries) GetSquadCaptain(ctx context.Context, squadID uuid.UUID) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getSquadCaptain, squadID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Name,
		&i.ShortName,
		&i.Role,
		&i.Status,
		&i.ParentAgentID,
		&i.AdapterType,
		&i.AdapterConfig,
		&i.SystemPrompt,
		&i.Model,
		&i.BudgetMonthlyCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentChildren = `-- name: ListAgentChildren :many
SELECT id, squad_id, name, short_name, role, status, parent_agent_id, adapter_type, adapter_config, system_prompt, model, budget_monthly_cents, created_at, updated_at FROM agents
WHERE parent_agent_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAgentChildren(ctx context.Context, parentAgentID uuid.NullUUID) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentChildren, parentAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.Name,
			&i.ShortName,
			&i.Role,
			&i.Status,
			&i.ParentAgentID,
			&i.AdapterType,
			&i.AdapterConfig,
			&i.SystemPrompt,
			&i.Model,
			&i.BudgetMonthlyCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsBySquad = `-- name: ListAgentsBySquad :many
SELECT id, squad_id, name, short_name, role, status, parent_agent_id, adapter_type, adapter_config, system_prompt, model, budget_monthly_cents, created_at, updated_at FROM agents
WHERE squad_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAgentsBySquad(ctx context.Context, squadID uuid.UUID) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentsBySquad, squadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.Name,
			&i.ShortName,
			&i.Role,
			&i.Status,
			&i.ParentAgentID,
			&i.AdapterType,
			&i.AdapterConfig,
			&i.SystemPrompt,
			&i.Model,
			&i.BudgetMonthlyCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents SET
    name = COALESCE($1, name),
    short_name = COALESCE($2, short_name),
    role = COALESCE($3, role),
    status = COALESCE($4, status),
    parent_agent_id = CASE
        WHEN $5::boolean THEN $6
        ELSE parent_agent_id
    END,
    adapter_type = COALESCE($7, adapter_type),
    adapter_config = COALESCE($8, adapter_config),
    system_prompt = COALESCE($9, system_prompt),
    model = COALESCE($10, model),
    budget_monthly_cents = CASE
        WHEN $11::boolean THEN $12
        ELSE budget_monthly_cents
    END
WHERE id = $13
RETURNING id, squad_id, name, short_name, role, status, parent_agent_id, adapter_type, adapter_config, system_prompt, model, budget_monthly_cents, created_at, updated_at
`

type UpdateAgentParams struct {
	Name               sql.NullString        `json:"name"`
	ShortName          sql.NullString        `json:"short_name"`
	Role               NullAgentRole         `json:"role"`
	Status             NullAgentStatus       `json:"status"`
	SetParent          bool                  `json:"set_parent"`
	ParentAgentID      uuid.NullUUID         `json:"parent_agent_id"`
	AdapterType        NullAdapterType       `json:"adapter_type"`
	AdapterConfig      pqtype.NullRawMessage `json:"adapter_config"`
	SystemPrompt       sql.NullString        `json:"system_prompt"`
	Model              sql.NullString        `json:"model"`
	SetBudget          bool                  `json:"set_budget"`
	BudgetMonthlyCents sql.NullInt64         `json:"budget_monthly_cents"`
	ID                 uuid.UUID             `json:"id"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, updateAgent,
		arg.Name,
		arg.ShortName,
		arg.Role,
		arg.Status,
		arg.SetParent,
		arg.ParentAgentID,
		arg.AdapterType,
		arg.AdapterConfig,
		arg.SystemPrompt,
		arg.Model,
		arg.SetBudget,
		arg.BudgetMonthlyCents,
		arg.ID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Name,
		&i.ShortName,
		&i.Role,
		&i.Status,
		&i.ParentAgentID,
		&i.AdapterType,
		&i.AdapterConfig,
		&i.SystemPrompt,
		&i.Model,
		&i.BudgetMonthlyCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
