// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getConversationSession = `-- name: GetConversationSession :one
SELECT session_state FROM agent_conversation_sessions
WHERE agent_id = $1 AND issue_id = $2
`

type GetConversationSessionParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	IssueID uuid.UUID `json:"issue_id"`
}

func (q *Queries) GetConversationSession(ctx context.Context, arg GetConversationSessionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getConversationSession, arg.AgentID, arg.IssueID)
	var session_state string
	err := row.Scan(&session_state)
	return session_state, err
}

const getTaskSession = `-- name: GetTaskSession :one
SELECT session_state FROM agent_task_sessions
WHERE agent_id = $1 AND issue_id = $2
`

type GetTaskSessionParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	IssueID uuid.UUID `json:"issue_id"`
}

func (q *Queries) GetTaskSession(ctx context.Context, arg GetTaskSessionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getTaskSession, arg.AgentID, arg.IssueID)
	var session_state string
	err := row.Scan(&session_state)
	return session_state, err
}

const upsertConversationSession = `-- name: UpsertConversationSession :exec
INSERT INTO agent_conversation_sessions (agent_id, issue_id, session_state)
VALUES ($1, $2, $3)
ON CONFLICT (agent_id, issue_id) DO UPDATE
    SET session_state = EXCLUDED.session_state,
        updated_at    = now()
`

type UpsertConversationSessionParams struct {
	AgentID      uuid.UUID `json:"agent_id"`
	IssueID      uuid.UUID `json:"issue_id"`
	SessionState string    `json:"session_state"`
}

func (q *Queries) UpsertConversationSession(ctx context.Context, arg UpsertConversationSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertConversationSession, arg.AgentID, arg.IssueID, arg.SessionState)
	return err
}

const upsertTaskSession = `-- name: UpsertTaskSession :exec
INSERT INTO agent_task_sessions (agent_id, issue_id, session_state)
VALUES ($1, $2, $3)
ON CONFLICT (agent_id, issue_id) DO UPDATE
    SET session_state = EXCLUDED.session_state,
        updated_at    = now()
`

type UpsertTaskSessionParams struct {
	AgentID      uuid.UUID `json:"agent_id"`
	IssueID      uuid.UUID `json:"issue_id"`
	SessionState string    `json:"session_state"`
}

func (q *Queries) UpsertTaskSession(ctx context.Context, arg UpsertTaskSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertTaskSession, arg.AgentID, arg.IssueID, arg.SessionState)
	return err
}
