// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cost_events.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const getAgentCostBreakdown = `-- name: GetAgentCostBreakdown :many
SELECT
    ce.agent_id,
    a.name AS agent_name,
    a.short_name AS agent_short_name,
    COALESCE(SUM(ce.amount_cents), 0)::BIGINT AS total_cents,
    COUNT(*)::BIGINT AS event_count
FROM cost_events ce
JOIN agents a ON a.id = ce.agent_id
WHERE ce.squad_id = $1
  AND ce.created_at >= $2
  AND ce.created_at < $3
GROUP BY ce.agent_id, a.name, a.short_name
ORDER BY total_cents DESC
`

type GetAgentCostBreakdownParams struct {
	SquadID     uuid.UUID `json:"squad_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

type GetAgentCostBreakdownRow struct {
	AgentID        uuid.UUID `json:"agent_id"`
	AgentName      string    `json:"agent_name"`
	AgentShortName string    `json:"agent_short_name"`
	TotalCents     int64     `json:"total_cents"`
	EventCount     int64     `json:"event_count"`
}

func (q *Queries) GetAgentCostBreakdown(ctx context.Context, arg GetAgentCostBreakdownParams) ([]GetAgentCostBreakdownRow, error) {
	rows, err := q.db.QueryContext(ctx, getAgentCostBreakdown, arg.SquadID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAgentCostBreakdownRow{}
	for rows.Next() {
		var i GetAgentCostBreakdownRow
		if err := rows.Scan(
			&i.AgentID,
			&i.AgentName,
			&i.AgentShortName,
			&i.TotalCents,
			&i.EventCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentMonthlySpend = `-- name: GetAgentMonthlySpend :one
SELECT COALESCE(SUM(amount_cents), 0)::BIGINT AS total_cents
FROM cost_events
WHERE agent_id = $1
  AND created_at >= $2
  AND created_at < $3
`

type GetAgentMonthlySpendParams struct {
	AgentID     uuid.UUID `json:"agent_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

func (q *Queries) GetAgentMonthlySpend(ctx context.Context, arg GetAgentMonthlySpendParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAgentMonthlySpend, arg.AgentID, arg.PeriodStart, arg.PeriodEnd)
	var total_cents int64
	err := row.Scan(&total_cents)
	return total_cents, err
}

const getCostTrendsDaily = `-- name: GetCostTrendsDaily :many
SELECT date_trunc('day', created_at)::timestamptz AS bucket,
       COALESCE(SUM(amount_cents), 0)::bigint AS total_cents,
       COUNT(*)::bigint AS event_count
FROM cost_events
WHERE squad_id = $1 AND created_at >= $2 AND created_at < $3
GROUP BY bucket ORDER BY bucket ASC
`

type GetCostTrendsDailyParams struct {
	SquadID     uuid.UUID `json:"squad_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

type GetCostTrendsDailyRow struct {
	Bucket     time.Time `json:"bucket"`
	TotalCents int64     `json:"total_cents"`
	EventCount int64     `json:"event_count"`
}

func (q *Queries) GetCostTrendsDaily(ctx context.Context, arg GetCostTrendsDailyParams) ([]GetCostTrendsDailyRow, error) {
	rows, err := q.db.QueryContext(ctx, getCostTrendsDaily, arg.SquadID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCostTrendsDailyRow{}
	for rows.Next() {
		var i GetCostTrendsDailyRow
		if err := rows.Scan(&i.Bucket, &i.TotalCents, &i.EventCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCostTrendsMonthly = `-- name: GetCostTrendsMonthly :many
SELECT date_trunc('month', created_at)::timestamptz AS bucket,
       COALESCE(SUM(amount_cents), 0)::bigint AS total_cents,
       COUNT(*)::bigint AS event_count
FROM cost_events
WHERE squad_id = $1 AND created_at >= $2 AND created_at < $3
GROUP BY bucket ORDER BY bucket ASC
`

type GetCostTrendsMonthlyParams struct {
	SquadID     uuid.UUID `json:"squad_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

type GetCostTrendsMonthlyRow struct {
	Bucket     time.Time `json:"bucket"`
	TotalCents int64     `json:"total_cents"`
	EventCount int64     `json:"event_count"`
}

func (q *Queries) GetCostTrendsMonthly(ctx context.Context, arg GetCostTrendsMonthlyParams) ([]GetCostTrendsMonthlyRow, error) {
	rows, err := q.db.QueryContext(ctx, getCostTrendsMonthly, arg.SquadID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCostTrendsMonthlyRow{}
	for rows.Next() {
		var i GetCostTrendsMonthlyRow
		if err := rows.Scan(&i.Bucket, &i.TotalCents, &i.EventCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCostTrendsWeekly = `-- name: GetCostTrendsWeekly :many
SELECT date_trunc('week', created_at)::timestamptz AS bucket,
       COALESCE(SUM(amount_cents), 0)::bigint AS total_cents,
       COUNT(*)::bigint AS event_count
FROM cost_events
WHERE squad_id = $1 AND created_at >= $2 AND created_at < $3
GROUP BY bucket ORDER BY bucket ASC
`

type GetCostTrendsWeeklyParams struct {
	SquadID     uuid.UUID `json:"squad_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

type GetCostTrendsWeeklyRow struct {
	Bucket     time.Time `json:"bucket"`
	TotalCents int64     `json:"total_cents"`
	EventCount int64     `json:"event_count"`
}

func (q *Queries) GetCostTrendsWeekly(ctx context.Context, arg GetCostTrendsWeeklyParams) ([]GetCostTrendsWeeklyRow, error) {
	rows, err := q.db.QueryContext(ctx, getCostTrendsWeekly, arg.SquadID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCostTrendsWeeklyRow{}
	for rows.Next() {
		var i GetCostTrendsWeeklyRow
		if err := rows.Scan(&i.Bucket, &i.TotalCents, &i.EventCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSquadMonthlySpend = `-- name: GetSquadMonthlySpend :one
SELECT COALESCE(SUM(amount_cents), 0)::BIGINT AS total_cents
FROM cost_events
WHERE squad_id = $1
  AND created_at >= $2
  AND created_at < $3
`

type GetSquadMonthlySpendParams struct {
	SquadID     uuid.UUID `json:"squad_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

func (q *Queries) GetSquadMonthlySpend(ctx context.Context, arg GetSquadMonthlySpendParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSquadMonthlySpend, arg.SquadID, arg.PeriodStart, arg.PeriodEnd)
	var total_cents int64
	err := row.Scan(&total_cents)
	return total_cents, err
}

const insertCostEvent = `-- name: InsertCostEvent :one
INSERT INTO cost_events (
    squad_id, agent_id, amount_cents, event_type,
    model, input_tokens, output_tokens, metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, squad_id, agent_id, amount_cents, event_type, model, input_tokens, output_tokens, metadata, created_at
`

type InsertCostEventParams struct {
	SquadID      uuid.UUID             `json:"squad_id"`
	AgentID      uuid.UUID             `json:"agent_id"`
	AmountCents  int64                 `json:"amount_cents"`
	EventType    string                `json:"event_type"`
	Model        sql.NullString        `json:"model"`
	InputTokens  sql.NullInt64         `json:"input_tokens"`
	OutputTokens sql.NullInt64         `json:"output_tokens"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) InsertCostEvent(ctx context.Context, arg InsertCostEventParams) (CostEvent, error) {
	row := q.db.QueryRowContext(ctx, insertCostEvent,
		arg.SquadID,
		arg.AgentID,
		arg.AmountCents,
		arg.EventType,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.Metadata,
	)
	var i CostEvent
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.AgentID,
		&i.AmountCents,
		&i.EventType,
		&i.Model,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listRunningIdleAgentsBySquad = `-- name: ListRunningIdleAgentsBySquad :many
SELECT id, squad_id, name, short_name, role, status, parent_agent_id, adapter_type, adapter_config, system_prompt, model, budget_monthly_cents, created_at, updated_at FROM agents
WHERE squad_id = $1
  AND status IN ('running', 'idle')
ORDER BY created_at ASC
`

func (q *Queries) ListRunningIdleAgentsBySquad(ctx context.Context, squadID uuid.UUID) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listRunningIdleAgentsBySquad, squadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.Name,
			&i.ShortName,
			&i.Role,
			&i.Status,
			&i.ParentAgentID,
			&i.AdapterType,
			&i.AdapterConfig,
			&i.SystemPrompt,
			&i.Model,
			&i.BudgetMonthlyCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
