// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goals.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countGoalChildren = `-- name: CountGoalChildren :one
SELECT count(*) FROM goals WHERE parent_id = $1
`

func (q *Queries) CountGoalChildren(ctx context.Context, parentID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGoalChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (squad_id, parent_id, title, description)
VALUES ($1, $2, $3, $4)
RETURNING id, squad_id, parent_id, title, description, status, created_at, updated_at
`

type CreateGoalParams struct {
	SquadID     uuid.UUID      `json:"squad_id"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, createGoal,
		arg.SquadID,
		arg.ParentID,
		arg.Title,
		arg.Description,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGoalAncestors = `-- name: GetGoalAncestors :many
WITH RECURSIVE ancestors AS (
    SELECT parent_id, 1 AS depth
    FROM goals
    WHERE goals.id = $1
    UNION ALL
    SELECT g.parent_id, a.depth + 1
    FROM goals g
    JOIN ancestors a ON g.id = a.parent_id
    WHERE a.depth < 6 AND a.parent_id IS NOT NULL
)
SELECT parent_id::UUID AS ancestor_id FROM ancestors WHERE parent_id IS NOT NULL
`

func (q *Queries) GetGoalAncestors(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getGoalAncestors, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var ancestor_id uuid.UUID
		if err := rows.Scan(&ancestor_id); err != nil {
			return nil, err
		}
		items = append(items, ancestor_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoalByID = `-- name: GetGoalByID :one
SELECT id, squad_id, parent_id, title, description, status, created_at, updated_at FROM goals WHERE id = $1
`

func (q *Queries) GetGoalByID(ctx context.Context, id uuid.UUID) (Goal, error) {
	row := q.db.QueryRowContext(ctx, getGoalByID, id)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGoalsBySquad = `-- name: ListGoalsBySquad :many
SELECT id, squad_id, parent_id, title, description, status, created_at, updated_at FROM goals WHERE squad_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListGoalsBySquad(ctx context.Context, squadID uuid.UUID) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listGoalsBySquad, squadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsBySquadAndParent = `-- name: ListGoalsBySquadAndParent :many
SELECT id, squad_id, parent_id, title, description, status, created_at, updated_at FROM goals WHERE squad_id = $1 AND parent_id = $2 ORDER BY created_at DESC
`

type ListGoalsBySquadAndParentParams struct {
	SquadID  uuid.UUID     `json:"squad_id"`
	ParentID uuid.NullUUID `json:"parent_id"`
}

func (q *Queries) ListGoalsBySquadAndParent(ctx context.Context, arg ListGoalsBySquadAndParentParams) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listGoalsBySquadAndParent, arg.SquadID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopLevelGoalsBySquad = `-- name: ListTopLevelGoalsBySquad :many
SELECT id, squad_id, parent_id, title, description, status, created_at, updated_at FROM goals WHERE squad_id = $1 AND parent_id IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListTopLevelGoalsBySquad(ctx context.Context, squadID uuid.UUID) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listTopLevelGoalsBySquad, squadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET
    title       = COALESCE($1, title),
    description = CASE WHEN $2::boolean THEN $3 ELSE description END,
    parent_id   = CASE WHEN $4::boolean THEN $5 ELSE parent_id END,
    status      = COALESCE($6, status)
WHERE id = $7
RETURNING id, squad_id, parent_id, title, description, status, created_at, updated_at
`

type UpdateGoalParams struct {
	Title          sql.NullString `json:"title"`
	SetDescription bool           `json:"set_description"`
	Description    sql.NullString `json:"description"`
	SetParent      bool           `json:"set_parent"`
	ParentID       uuid.NullUUID  `json:"parent_id"`
	Status         sql.NullString `json:"status"`
	ID             uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, updateGoal,
		arg.Title,
		arg.SetDescription,
		arg.Description,
		arg.SetParent,
		arg.ParentID,
		arg.Status,
		arg.ID,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
