// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goals.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countGoalChildren = `-- name: CountGoalChildren :one
SELECT count(*) FROM goals WHERE parent_id = $1
`

func (q *Queries) CountGoalChildren(ctx context.Context, parentID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGoalChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (squad_id, parent_id, title, description)
VALUES ($1, $2, $3, $4)
RETURNING id, squad_id, parent_id, title, description, status, created_at, updated_at
`

type CreateGoalParams struct {
	SquadID     uuid.UUID      `json:"squad_id"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, createGoal,
		arg.SquadID,
		arg.ParentID,
		arg.Title,
		arg.Description,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGoalAncestors = `-- name: GetGoalAncestors :many
WITH RECURSIVE ancestors AS (
    SELECT parent_id, 1 AS depth
    FROM goals
    WHERE goals.id = $1
    UNION ALL
    SELECT g.parent_id, a.depth + 1
    FROM goals g
    JOIN ancestors a ON g.id = a.parent_id
    WHERE a.depth < 6 AND a.parent_id IS NOT NULL
)
SELECT parent_id::UUID AS ancestor_id FROM ancestors WHERE parent_id IS NOT NULL
`

func (q *Queries) GetGoalAncestors(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getGoalAncestors, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var ancestor_id uuid.UUID
		if err := rows.Scan(&ancestor_id); err != nil {
			return nil, err
		}
		items = append(items, ancestor_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoalByID = `-- name: GetGoalByID :one
SELECT id, squad_id, parent_id, title, description, status, created_at, updated_at FROM goals WHERE id = $1
`

func (q *Queries) GetGoalByID(ctx context.Context, id uuid.UUID) (Goal, error) {
	row := q.db.QueryRowContext(ctx, getGoalByID, id)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGoalMaxSubtreeDepth = `-- name: GetGoalMaxSubtreeDepth :one
WITH RECURSIVE subtree AS (
    SELECT goals.id, 1 AS depth
    FROM goals
    WHERE goals.parent_id = $1
    UNION ALL
    SELECT g.id, s.depth + 1
    FROM goals g
    JOIN subtree s ON g.parent_id = s.id
    WHERE s.depth < 10
)
SELECT COALESCE(MAX(depth), 0)::bigint AS max_depth FROM subtree
`

func (q *Queries) GetGoalMaxSubtreeDepth(ctx context.Context, goalID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getGoalMaxSubtreeDepth, goalID)
	var max_depth int64
	err := row.Scan(&max_depth)
	return max_depth, err
}

const getGoalsByIDs = `-- name: GetGoalsByIDs :many
SELECT id, squad_id, parent_id, title, description, status, created_at, updated_at FROM goals
WHERE id = ANY($1::UUID[])
ORDER BY title
`

func (q *Queries) GetGoalsByIDs(ctx context.Context, ids []uuid.UUID) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, getGoalsByIDs, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalLinkedIssuesByAgent = `-- name: ListGoalLinkedIssuesByAgent :many
SELECT i.goal_id, i.identifier
FROM issues i
WHERE i.squad_id = $1
  AND i.assignee_agent_id = $2
  AND i.goal_id IS NOT NULL
ORDER BY i.goal_id, i.created_at DESC
`

type ListGoalLinkedIssuesByAgentParams struct {
	SquadID uuid.UUID     `json:"squad_id"`
	AgentID uuid.NullUUID `json:"agent_id"`
}

type ListGoalLinkedIssuesByAgentRow struct {
	GoalID     uuid.NullUUID `json:"goal_id"`
	Identifier string        `json:"identifier"`
}

func (q *Queries) ListGoalLinkedIssuesByAgent(ctx context.Context, arg ListGoalLinkedIssuesByAgentParams) ([]ListGoalLinkedIssuesByAgentRow, error) {
	rows, err := q.db.QueryContext(ctx, listGoalLinkedIssuesByAgent, arg.SquadID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoalLinkedIssuesByAgentRow{}
	for rows.Next() {
		var i ListGoalLinkedIssuesByAgentRow
		if err := rows.Scan(&i.GoalID, &i.Identifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalLinkedIssuesByAgentIDs = `-- name: ListGoalLinkedIssuesByAgentIDs :many
SELECT i.goal_id, i.identifier
FROM issues i
WHERE i.squad_id = $1
  AND i.assignee_agent_id = ANY($2::UUID[])
  AND i.goal_id IS NOT NULL
ORDER BY i.goal_id, i.created_at DESC
`

type ListGoalLinkedIssuesByAgentIDsParams struct {
	SquadID  uuid.UUID   `json:"squad_id"`
	AgentIds []uuid.UUID `json:"agent_ids"`
}

type ListGoalLinkedIssuesByAgentIDsRow struct {
	GoalID     uuid.NullUUID `json:"goal_id"`
	Identifier string        `json:"identifier"`
}

func (q *Queries) ListGoalLinkedIssuesByAgentIDs(ctx context.Context, arg ListGoalLinkedIssuesByAgentIDsParams) ([]ListGoalLinkedIssuesByAgentIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGoalLinkedIssuesByAgentIDs, arg.SquadID, pq.Array(arg.AgentIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoalLinkedIssuesByAgentIDsRow{}
	for rows.Next() {
		var i ListGoalLinkedIssuesByAgentIDsRow
		if err := rows.Scan(&i.GoalID, &i.Identifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalLinkedIssuesBySquad = `-- name: ListGoalLinkedIssuesBySquad :many
SELECT i.goal_id, i.identifier
FROM issues i
WHERE i.squad_id = $1
  AND i.goal_id IS NOT NULL
ORDER BY i.goal_id, i.created_at DESC
`

type ListGoalLinkedIssuesBySquadRow struct {
	GoalID     uuid.NullUUID `json:"goal_id"`
	Identifier string        `json:"identifier"`
}

func (q *Queries) ListGoalLinkedIssuesBySquad(ctx context.Context, squadID uuid.UUID) ([]ListGoalLinkedIssuesBySquadRow, error) {
	rows, err := q.db.QueryContext(ctx, listGoalLinkedIssuesBySquad, squadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoalLinkedIssuesBySquadRow{}
	for rows.Next() {
		var i ListGoalLinkedIssuesBySquadRow
		if err := rows.Scan(&i.GoalID, &i.Identifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsBySquad = `-- name: ListGoalsBySquad :many
SELECT id, squad_id, parent_id, title, description, status, created_at, updated_at FROM goals WHERE squad_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListGoalsBySquad(ctx context.Context, squadID uuid.UUID) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listGoalsBySquad, squadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsBySquadAndParent = `-- name: ListGoalsBySquadAndParent :many
SELECT id, squad_id, parent_id, title, description, status, created_at, updated_at FROM goals WHERE squad_id = $1 AND parent_id = $2 ORDER BY created_at DESC
`

type ListGoalsBySquadAndParentParams struct {
	SquadID  uuid.UUID     `json:"squad_id"`
	ParentID uuid.NullUUID `json:"parent_id"`
}

func (q *Queries) ListGoalsBySquadAndParent(ctx context.Context, arg ListGoalsBySquadAndParentParams) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listGoalsBySquadAndParent, arg.SquadID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopLevelGoalsBySquad = `-- name: ListTopLevelGoalsBySquad :many
SELECT id, squad_id, parent_id, title, description, status, created_at, updated_at FROM goals WHERE squad_id = $1 AND parent_id IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListTopLevelGoalsBySquad(ctx context.Context, squadID uuid.UUID) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listTopLevelGoalsBySquad, squadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET
    title       = COALESCE($1, title),
    description = CASE WHEN $2::boolean THEN $3 ELSE description END,
    parent_id   = CASE WHEN $4::boolean THEN $5 ELSE parent_id END,
    status      = COALESCE($6, status)
WHERE id = $7
RETURNING id, squad_id, parent_id, title, description, status, created_at, updated_at
`

type UpdateGoalParams struct {
	Title          sql.NullString `json:"title"`
	SetDescription bool           `json:"set_description"`
	Description    sql.NullString `json:"description"`
	SetParent      bool           `json:"set_parent"`
	ParentID       uuid.NullUUID  `json:"parent_id"`
	Status         sql.NullString `json:"status"`
	ID             uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, updateGoal,
		arg.Title,
		arg.SetDescription,
		arg.Description,
		arg.SetParent,
		arg.ParentID,
		arg.Status,
		arg.ID,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
