// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health.sql

package db

import (
	"context"
)

const ping = `-- name: Ping :exec
SELECT 1
`

func (q *Queries) Ping(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ping)
	return err
}
