// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: heartbeat_runs.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const cancelAllStaleHeartbeatRuns = `-- name: CancelAllStaleHeartbeatRuns :exec
UPDATE heartbeat_runs
SET status = 'cancelled', finished_at = now()
WHERE status IN ('queued', 'running')
  AND created_at < now() - interval '2 hours'
`

func (q *Queries) CancelAllStaleHeartbeatRuns(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cancelAllStaleHeartbeatRuns)
	return err
}

const cancelStaleHeartbeatRuns = `-- name: CancelStaleHeartbeatRuns :exec
UPDATE heartbeat_runs
SET status = 'cancelled', finished_at = now()
WHERE status IN ('queued', 'running')
  AND squad_id = $1
  AND created_at < now() - interval '2 hours'
`

func (q *Queries) CancelStaleHeartbeatRuns(ctx context.Context, squadID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, cancelStaleHeartbeatRuns, squadID)
	return err
}

const countActiveRunsBySquad = `-- name: CountActiveRunsBySquad :one
SELECT COUNT(*) FROM heartbeat_runs
WHERE squad_id = $1 AND status IN ('queued', 'running')
`

func (q *Queries) CountActiveRunsBySquad(ctx context.Context, squadID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveRunsBySquad, squadID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHeartbeatRun = `-- name: CreateHeartbeatRun :one
INSERT INTO heartbeat_runs (
    squad_id, agent_id, wakeup_request_id, invocation_source,
    status, session_id_before
)
VALUES (
    $1, $2, $3, $4,
    'queued', $5
)
RETURNING id, squad_id, agent_id, wakeup_request_id, invocation_source, status, session_id_before, session_id_after, exit_code, usage_json, stdout_excerpt, stderr_excerpt, started_at, finished_at, created_at
`

type CreateHeartbeatRunParams struct {
	SquadID          uuid.UUID              `json:"squad_id"`
	AgentID          uuid.UUID              `json:"agent_id"`
	WakeupRequestID  uuid.NullUUID          `json:"wakeup_request_id"`
	InvocationSource WakeupInvocationSource `json:"invocation_source"`
	SessionIDBefore  sql.NullString         `json:"session_id_before"`
}

func (q *Queries) CreateHeartbeatRun(ctx context.Context, arg CreateHeartbeatRunParams) (HeartbeatRun, error) {
	row := q.db.QueryRowContext(ctx, createHeartbeatRun,
		arg.SquadID,
		arg.AgentID,
		arg.WakeupRequestID,
		arg.InvocationSource,
		arg.SessionIDBefore,
	)
	var i HeartbeatRun
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.AgentID,
		&i.WakeupRequestID,
		&i.InvocationSource,
		&i.Status,
		&i.SessionIDBefore,
		&i.SessionIDAfter,
		&i.ExitCode,
		&i.UsageJson,
		&i.StdoutExcerpt,
		&i.StderrExcerpt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveRunByAgent = `-- name: GetActiveRunByAgent :one
SELECT id, squad_id, agent_id, wakeup_request_id, invocation_source, status, session_id_before, session_id_after, exit_code, usage_json, stdout_excerpt, stderr_excerpt, started_at, finished_at, created_at FROM heartbeat_runs
WHERE agent_id = $1 AND status IN ('queued', 'running')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveRunByAgent(ctx context.Context, agentID uuid.UUID) (HeartbeatRun, error) {
	row := q.db.QueryRowContext(ctx, getActiveRunByAgent, agentID)
	var i HeartbeatRun
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.AgentID,
		&i.WakeupRequestID,
		&i.InvocationSource,
		&i.Status,
		&i.SessionIDBefore,
		&i.SessionIDAfter,
		&i.ExitCode,
		&i.UsageJson,
		&i.StdoutExcerpt,
		&i.StderrExcerpt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentLastRun = `-- name: GetAgentLastRun :many
SELECT DISTINCT ON (agent_id) agent_id, id AS run_id, status, created_at
FROM heartbeat_runs
WHERE squad_id = $1
ORDER BY agent_id, created_at DESC
`

type GetAgentLastRunRow struct {
	AgentID   uuid.UUID          `json:"agent_id"`
	RunID     uuid.UUID          `json:"run_id"`
	Status    HeartbeatRunStatus `json:"status"`
	CreatedAt time.Time          `json:"created_at"`
}

func (q *Queries) GetAgentLastRun(ctx context.Context, squadID uuid.UUID) ([]GetAgentLastRunRow, error) {
	rows, err := q.db.QueryContext(ctx, getAgentLastRun, squadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAgentLastRunRow{}
	for rows.Next() {
		var i GetAgentLastRunRow
		if err := rows.Scan(
			&i.AgentID,
			&i.RunID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentRunStats = `-- name: GetAgentRunStats :many
SELECT a.id AS agent_id, a.name AS agent_name, a.status AS agent_status,
       COUNT(hr.id)::bigint AS total_runs,
       COUNT(hr.id) FILTER (WHERE hr.status = 'succeeded')::bigint AS success_count,
       COUNT(hr.id) FILTER (WHERE hr.status = 'failed')::bigint AS failure_count
FROM agents a
LEFT JOIN heartbeat_runs hr ON hr.agent_id = a.id
    AND hr.squad_id = $1
    AND hr.created_at >= $2 AND hr.created_at < $3
WHERE a.squad_id = $1
GROUP BY a.id, a.name, a.status
ORDER BY failure_count DESC, total_runs DESC
`

type GetAgentRunStatsParams struct {
	SquadID     uuid.UUID `json:"squad_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

type GetAgentRunStatsRow struct {
	AgentID      uuid.UUID   `json:"agent_id"`
	AgentName    string      `json:"agent_name"`
	AgentStatus  AgentStatus `json:"agent_status"`
	TotalRuns    int64       `json:"total_runs"`
	SuccessCount int64       `json:"success_count"`
	FailureCount int64       `json:"failure_count"`
}

func (q *Queries) GetAgentRunStats(ctx context.Context, arg GetAgentRunStatsParams) ([]GetAgentRunStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAgentRunStats, arg.SquadID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAgentRunStatsRow{}
	for rows.Next() {
		var i GetAgentRunStatsRow
		if err := rows.Scan(
			&i.AgentID,
			&i.AgentName,
			&i.AgentStatus,
			&i.TotalRuns,
			&i.SuccessCount,
			&i.FailureCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHeartbeatRunByID = `-- name: GetHeartbeatRunByID :one
SELECT id, squad_id, agent_id, wakeup_request_id, invocation_source, status, session_id_before, session_id_after, exit_code, usage_json, stdout_excerpt, stderr_excerpt, started_at, finished_at, created_at FROM heartbeat_runs WHERE id = $1
`

func (q *Queries) GetHeartbeatRunByID(ctx context.Context, id uuid.UUID) (HeartbeatRun, error) {
	row := q.db.QueryRowContext(ctx, getHeartbeatRunByID, id)
	var i HeartbeatRun
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.AgentID,
		&i.WakeupRequestID,
		&i.InvocationSource,
		&i.Status,
		&i.SessionIDBefore,
		&i.SessionIDAfter,
		&i.ExitCode,
		&i.UsageJson,
		&i.StdoutExcerpt,
		&i.StderrExcerpt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentRunsWithContext = `-- name: ListAgentRunsWithContext :many
SELECT
    hr.id, hr.squad_id, hr.agent_id, hr.wakeup_request_id, hr.invocation_source, hr.status, hr.session_id_before, hr.session_id_after, hr.exit_code, hr.usage_json, hr.stdout_excerpt, hr.stderr_excerpt, hr.started_at, hr.finished_at, hr.created_at,
    wr.context_json AS wakeup_context,
    COALESCE(i.identifier, '') AS issue_identifier,
    COALESCE(i.title, '') AS issue_title,
    COALESCE(i.id::text, '') AS issue_id
FROM heartbeat_runs hr
LEFT JOIN wakeup_requests wr ON wr.id = hr.wakeup_request_id
LEFT JOIN LATERAL (
    SELECT id, identifier, title
    FROM issues
    WHERE id = (wr.context_json->>'ARI_TASK_ID')::uuid
    LIMIT 1
) i ON true
WHERE hr.agent_id = $1
ORDER BY hr.created_at DESC
LIMIT $3 OFFSET $2
`

type ListAgentRunsWithContextParams struct {
	AgentID    uuid.UUID `json:"agent_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

type ListAgentRunsWithContextRow struct {
	ID               uuid.UUID              `json:"id"`
	SquadID          uuid.UUID              `json:"squad_id"`
	AgentID          uuid.UUID              `json:"agent_id"`
	WakeupRequestID  uuid.NullUUID          `json:"wakeup_request_id"`
	InvocationSource WakeupInvocationSource `json:"invocation_source"`
	Status           HeartbeatRunStatus     `json:"status"`
	SessionIDBefore  sql.NullString         `json:"session_id_before"`
	SessionIDAfter   sql.NullString         `json:"session_id_after"`
	ExitCode         sql.NullInt32          `json:"exit_code"`
	UsageJson        pqtype.NullRawMessage  `json:"usage_json"`
	StdoutExcerpt    sql.NullString         `json:"stdout_excerpt"`
	StderrExcerpt    sql.NullString         `json:"stderr_excerpt"`
	StartedAt        sql.NullTime           `json:"started_at"`
	FinishedAt       sql.NullTime           `json:"finished_at"`
	CreatedAt        time.Time              `json:"created_at"`
	WakeupContext    pqtype.NullRawMessage  `json:"wakeup_context"`
	IssueIdentifier  string                 `json:"issue_identifier"`
	IssueTitle       string                 `json:"issue_title"`
	IssueID          interface{}            `json:"issue_id"`
}

func (q *Queries) ListAgentRunsWithContext(ctx context.Context, arg ListAgentRunsWithContextParams) ([]ListAgentRunsWithContextRow, error) {
	rows, err := q.db.QueryContext(ctx, listAgentRunsWithContext, arg.AgentID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentRunsWithContextRow{}
	for rows.Next() {
		var i ListAgentRunsWithContextRow
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.AgentID,
			&i.WakeupRequestID,
			&i.InvocationSource,
			&i.Status,
			&i.SessionIDBefore,
			&i.SessionIDAfter,
			&i.ExitCode,
			&i.UsageJson,
			&i.StdoutExcerpt,
			&i.StderrExcerpt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.WakeupContext,
			&i.IssueIdentifier,
			&i.IssueTitle,
			&i.IssueID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeartbeatRunsByAgent = `-- name: ListHeartbeatRunsByAgent :many
SELECT id, squad_id, agent_id, wakeup_request_id, invocation_source, status, session_id_before, session_id_after, exit_code, usage_json, stdout_excerpt, stderr_excerpt, started_at, finished_at, created_at FROM heartbeat_runs
WHERE agent_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListHeartbeatRunsByAgentParams struct {
	AgentID    uuid.UUID `json:"agent_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

func (q *Queries) ListHeartbeatRunsByAgent(ctx context.Context, arg ListHeartbeatRunsByAgentParams) ([]HeartbeatRun, error) {
	rows, err := q.db.QueryContext(ctx, listHeartbeatRunsByAgent, arg.AgentID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeartbeatRun{}
	for rows.Next() {
		var i HeartbeatRun
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.AgentID,
			&i.WakeupRequestID,
			&i.InvocationSource,
			&i.Status,
			&i.SessionIDBefore,
			&i.SessionIDAfter,
			&i.ExitCode,
			&i.UsageJson,
			&i.StdoutExcerpt,
			&i.StderrExcerpt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeartbeatRunsBySquad = `-- name: ListHeartbeatRunsBySquad :many
SELECT id, squad_id, agent_id, wakeup_request_id, invocation_source, status, session_id_before, session_id_after, exit_code, usage_json, stdout_excerpt, stderr_excerpt, started_at, finished_at, created_at FROM heartbeat_runs
WHERE squad_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListHeartbeatRunsBySquadParams struct {
	SquadID    uuid.UUID `json:"squad_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

func (q *Queries) ListHeartbeatRunsBySquad(ctx context.Context, arg ListHeartbeatRunsBySquadParams) ([]HeartbeatRun, error) {
	rows, err := q.db.QueryContext(ctx, listHeartbeatRunsBySquad, arg.SquadID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeartbeatRun{}
	for rows.Next() {
		var i HeartbeatRun
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.AgentID,
			&i.WakeupRequestID,
			&i.InvocationSource,
			&i.Status,
			&i.SessionIDBefore,
			&i.SessionIDAfter,
			&i.ExitCode,
			&i.UsageJson,
			&i.StdoutExcerpt,
			&i.StderrExcerpt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHeartbeatRunFinished = `-- name: UpdateHeartbeatRunFinished :one
UPDATE heartbeat_runs
SET status = $1,
    exit_code = $2,
    usage_json = $3,
    session_id_after = $4,
    stdout_excerpt = $5,
    stderr_excerpt = $6,
    finished_at = now()
WHERE id = $7
RETURNING id, squad_id, agent_id, wakeup_request_id, invocation_source, status, session_id_before, session_id_after, exit_code, usage_json, stdout_excerpt, stderr_excerpt, started_at, finished_at, created_at
`

type UpdateHeartbeatRunFinishedParams struct {
	Status         HeartbeatRunStatus    `json:"status"`
	ExitCode       sql.NullInt32         `json:"exit_code"`
	UsageJson      pqtype.NullRawMessage `json:"usage_json"`
	SessionIDAfter sql.NullString        `json:"session_id_after"`
	StdoutExcerpt  sql.NullString        `json:"stdout_excerpt"`
	StderrExcerpt  sql.NullString        `json:"stderr_excerpt"`
	ID             uuid.UUID             `json:"id"`
}

func (q *Queries) UpdateHeartbeatRunFinished(ctx context.Context, arg UpdateHeartbeatRunFinishedParams) (HeartbeatRun, error) {
	row := q.db.QueryRowContext(ctx, updateHeartbeatRunFinished,
		arg.Status,
		arg.ExitCode,
		arg.UsageJson,
		arg.SessionIDAfter,
		arg.StdoutExcerpt,
		arg.StderrExcerpt,
		arg.ID,
	)
	var i HeartbeatRun
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.AgentID,
		&i.WakeupRequestID,
		&i.InvocationSource,
		&i.Status,
		&i.SessionIDBefore,
		&i.SessionIDAfter,
		&i.ExitCode,
		&i.UsageJson,
		&i.StdoutExcerpt,
		&i.StderrExcerpt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateHeartbeatRunStarted = `-- name: UpdateHeartbeatRunStarted :one
UPDATE heartbeat_runs
SET status = 'running', started_at = now()
WHERE id = $1
RETURNING id, squad_id, agent_id, wakeup_request_id, invocation_source, status, session_id_before, session_id_after, exit_code, usage_json, stdout_excerpt, stderr_excerpt, started_at, finished_at, created_at
`

func (q *Queries) UpdateHeartbeatRunStarted(ctx context.Context, id uuid.UUID) (HeartbeatRun, error) {
	row := q.db.QueryRowContext(ctx, updateHeartbeatRunStarted, id)
	var i HeartbeatRun
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.AgentID,
		&i.WakeupRequestID,
		&i.InvocationSource,
		&i.Status,
		&i.SessionIDBefore,
		&i.SessionIDAfter,
		&i.ExitCode,
		&i.UsageJson,
		&i.StdoutExcerpt,
		&i.StderrExcerpt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}
