// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: heartbeat_runs.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const cancelStaleHeartbeatRuns = `-- name: CancelStaleHeartbeatRuns :exec
UPDATE heartbeat_runs
SET status = 'cancelled', finished_at = now()
WHERE status IN ('queued', 'running')
`

func (q *Queries) CancelStaleHeartbeatRuns(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cancelStaleHeartbeatRuns)
	return err
}

const countActiveRunsBySquad = `-- name: CountActiveRunsBySquad :one
SELECT COUNT(*) FROM heartbeat_runs
WHERE squad_id = $1 AND status IN ('queued', 'running')
`

func (q *Queries) CountActiveRunsBySquad(ctx context.Context, squadID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveRunsBySquad, squadID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHeartbeatRun = `-- name: CreateHeartbeatRun :one
INSERT INTO heartbeat_runs (
    squad_id, agent_id, wakeup_request_id, invocation_source,
    status, session_id_before
)
VALUES (
    $1, $2, $3, $4,
    'queued', $5
)
RETURNING id, squad_id, agent_id, wakeup_request_id, invocation_source, status, session_id_before, session_id_after, exit_code, usage_json, stdout_excerpt, stderr_excerpt, started_at, finished_at, created_at
`

type CreateHeartbeatRunParams struct {
	SquadID          uuid.UUID              `json:"squad_id"`
	AgentID          uuid.UUID              `json:"agent_id"`
	WakeupRequestID  uuid.NullUUID          `json:"wakeup_request_id"`
	InvocationSource WakeupInvocationSource `json:"invocation_source"`
	SessionIDBefore  sql.NullString         `json:"session_id_before"`
}

func (q *Queries) CreateHeartbeatRun(ctx context.Context, arg CreateHeartbeatRunParams) (HeartbeatRun, error) {
	row := q.db.QueryRowContext(ctx, createHeartbeatRun,
		arg.SquadID,
		arg.AgentID,
		arg.WakeupRequestID,
		arg.InvocationSource,
		arg.SessionIDBefore,
	)
	var i HeartbeatRun
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.AgentID,
		&i.WakeupRequestID,
		&i.InvocationSource,
		&i.Status,
		&i.SessionIDBefore,
		&i.SessionIDAfter,
		&i.ExitCode,
		&i.UsageJson,
		&i.StdoutExcerpt,
		&i.StderrExcerpt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveRunByAgent = `-- name: GetActiveRunByAgent :one
SELECT id, squad_id, agent_id, wakeup_request_id, invocation_source, status, session_id_before, session_id_after, exit_code, usage_json, stdout_excerpt, stderr_excerpt, started_at, finished_at, created_at FROM heartbeat_runs
WHERE agent_id = $1 AND status IN ('queued', 'running')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveRunByAgent(ctx context.Context, agentID uuid.UUID) (HeartbeatRun, error) {
	row := q.db.QueryRowContext(ctx, getActiveRunByAgent, agentID)
	var i HeartbeatRun
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.AgentID,
		&i.WakeupRequestID,
		&i.InvocationSource,
		&i.Status,
		&i.SessionIDBefore,
		&i.SessionIDAfter,
		&i.ExitCode,
		&i.UsageJson,
		&i.StdoutExcerpt,
		&i.StderrExcerpt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getHeartbeatRunByID = `-- name: GetHeartbeatRunByID :one
SELECT id, squad_id, agent_id, wakeup_request_id, invocation_source, status, session_id_before, session_id_after, exit_code, usage_json, stdout_excerpt, stderr_excerpt, started_at, finished_at, created_at FROM heartbeat_runs WHERE id = $1
`

func (q *Queries) GetHeartbeatRunByID(ctx context.Context, id uuid.UUID) (HeartbeatRun, error) {
	row := q.db.QueryRowContext(ctx, getHeartbeatRunByID, id)
	var i HeartbeatRun
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.AgentID,
		&i.WakeupRequestID,
		&i.InvocationSource,
		&i.Status,
		&i.SessionIDBefore,
		&i.SessionIDAfter,
		&i.ExitCode,
		&i.UsageJson,
		&i.StdoutExcerpt,
		&i.StderrExcerpt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listHeartbeatRunsByAgent = `-- name: ListHeartbeatRunsByAgent :many
SELECT id, squad_id, agent_id, wakeup_request_id, invocation_source, status, session_id_before, session_id_after, exit_code, usage_json, stdout_excerpt, stderr_excerpt, started_at, finished_at, created_at FROM heartbeat_runs
WHERE agent_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListHeartbeatRunsByAgentParams struct {
	AgentID    uuid.UUID `json:"agent_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

func (q *Queries) ListHeartbeatRunsByAgent(ctx context.Context, arg ListHeartbeatRunsByAgentParams) ([]HeartbeatRun, error) {
	rows, err := q.db.QueryContext(ctx, listHeartbeatRunsByAgent, arg.AgentID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeartbeatRun{}
	for rows.Next() {
		var i HeartbeatRun
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.AgentID,
			&i.WakeupRequestID,
			&i.InvocationSource,
			&i.Status,
			&i.SessionIDBefore,
			&i.SessionIDAfter,
			&i.ExitCode,
			&i.UsageJson,
			&i.StdoutExcerpt,
			&i.StderrExcerpt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeartbeatRunsBySquad = `-- name: ListHeartbeatRunsBySquad :many
SELECT id, squad_id, agent_id, wakeup_request_id, invocation_source, status, session_id_before, session_id_after, exit_code, usage_json, stdout_excerpt, stderr_excerpt, started_at, finished_at, created_at FROM heartbeat_runs
WHERE squad_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListHeartbeatRunsBySquadParams struct {
	SquadID    uuid.UUID `json:"squad_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

func (q *Queries) ListHeartbeatRunsBySquad(ctx context.Context, arg ListHeartbeatRunsBySquadParams) ([]HeartbeatRun, error) {
	rows, err := q.db.QueryContext(ctx, listHeartbeatRunsBySquad, arg.SquadID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeartbeatRun{}
	for rows.Next() {
		var i HeartbeatRun
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.AgentID,
			&i.WakeupRequestID,
			&i.InvocationSource,
			&i.Status,
			&i.SessionIDBefore,
			&i.SessionIDAfter,
			&i.ExitCode,
			&i.UsageJson,
			&i.StdoutExcerpt,
			&i.StderrExcerpt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHeartbeatRunFinished = `-- name: UpdateHeartbeatRunFinished :one
UPDATE heartbeat_runs
SET status = $1,
    exit_code = $2,
    usage_json = $3,
    session_id_after = $4,
    stdout_excerpt = $5,
    stderr_excerpt = $6,
    finished_at = now()
WHERE id = $7
RETURNING id, squad_id, agent_id, wakeup_request_id, invocation_source, status, session_id_before, session_id_after, exit_code, usage_json, stdout_excerpt, stderr_excerpt, started_at, finished_at, created_at
`

type UpdateHeartbeatRunFinishedParams struct {
	Status         HeartbeatRunStatus    `json:"status"`
	ExitCode       sql.NullInt32         `json:"exit_code"`
	UsageJson      pqtype.NullRawMessage `json:"usage_json"`
	SessionIDAfter sql.NullString        `json:"session_id_after"`
	StdoutExcerpt  sql.NullString        `json:"stdout_excerpt"`
	StderrExcerpt  sql.NullString        `json:"stderr_excerpt"`
	ID             uuid.UUID             `json:"id"`
}

func (q *Queries) UpdateHeartbeatRunFinished(ctx context.Context, arg UpdateHeartbeatRunFinishedParams) (HeartbeatRun, error) {
	row := q.db.QueryRowContext(ctx, updateHeartbeatRunFinished,
		arg.Status,
		arg.ExitCode,
		arg.UsageJson,
		arg.SessionIDAfter,
		arg.StdoutExcerpt,
		arg.StderrExcerpt,
		arg.ID,
	)
	var i HeartbeatRun
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.AgentID,
		&i.WakeupRequestID,
		&i.InvocationSource,
		&i.Status,
		&i.SessionIDBefore,
		&i.SessionIDAfter,
		&i.ExitCode,
		&i.UsageJson,
		&i.StdoutExcerpt,
		&i.StderrExcerpt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateHeartbeatRunStarted = `-- name: UpdateHeartbeatRunStarted :one
UPDATE heartbeat_runs
SET status = 'running', started_at = now()
WHERE id = $1
RETURNING id, squad_id, agent_id, wakeup_request_id, invocation_source, status, session_id_before, session_id_after, exit_code, usage_json, stdout_excerpt, stderr_excerpt, started_at, finished_at, created_at
`

func (q *Queries) UpdateHeartbeatRunStarted(ctx context.Context, id uuid.UUID) (HeartbeatRun, error) {
	row := q.db.QueryRowContext(ctx, updateHeartbeatRunStarted, id)
	var i HeartbeatRun
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.AgentID,
		&i.WakeupRequestID,
		&i.InvocationSource,
		&i.Status,
		&i.SessionIDBefore,
		&i.SessionIDAfter,
		&i.ExitCode,
		&i.UsageJson,
		&i.StdoutExcerpt,
		&i.StderrExcerpt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}
