// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox_items.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const acknowledgeInboxItem = `-- name: AcknowledgeInboxItem :one
UPDATE inbox_items SET
    status = 'acknowledged',
    acknowledged_by_user_id = $2,
    acknowledged_at = now(),
    updated_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, squad_id, category, type, status, urgency, title, body, payload, requested_by_agent_id, related_agent_id, related_issue_id, related_run_id, resolution, response_note, response_payload, resolved_by_user_id, resolved_at, acknowledged_by_user_id, acknowledged_at, created_at, updated_at, expires_at
`

type AcknowledgeInboxItemParams struct {
	ID                   uuid.UUID     `json:"id"`
	AcknowledgedByUserID uuid.NullUUID `json:"acknowledged_by_user_id"`
}

func (q *Queries) AcknowledgeInboxItem(ctx context.Context, arg AcknowledgeInboxItemParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, acknowledgeInboxItem, arg.ID, arg.AcknowledgedByUserID)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Category,
		&i.Type,
		&i.Status,
		&i.Urgency,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.RequestedByAgentID,
		&i.RelatedAgentID,
		&i.RelatedIssueID,
		&i.RelatedRunID,
		&i.Resolution,
		&i.ResponseNote,
		&i.ResponsePayload,
		&i.ResolvedByUserID,
		&i.ResolvedAt,
		&i.AcknowledgedByUserID,
		&i.AcknowledgedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const autoResolveInboxItem = `-- name: AutoResolveInboxItem :one
UPDATE inbox_items SET
    status = 'resolved',
    resolution = $1,
    response_note = $2,
    resolved_by_user_id = NULL,
    resolved_at = now(),
    updated_at = now()
WHERE id = $3 AND status IN ('pending', 'acknowledged')
RETURNING id, squad_id, category, type, status, urgency, title, body, payload, requested_by_agent_id, related_agent_id, related_issue_id, related_run_id, resolution, response_note, response_payload, resolved_by_user_id, resolved_at, acknowledged_by_user_id, acknowledged_at, created_at, updated_at, expires_at
`

type AutoResolveInboxItemParams struct {
	Resolution   NullInboxResolution `json:"resolution"`
	ResponseNote sql.NullString      `json:"response_note"`
	ID           uuid.UUID           `json:"id"`
}

func (q *Queries) AutoResolveInboxItem(ctx context.Context, arg AutoResolveInboxItemParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, autoResolveInboxItem, arg.Resolution, arg.ResponseNote, arg.ID)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Category,
		&i.Type,
		&i.Status,
		&i.Urgency,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.RequestedByAgentID,
		&i.RelatedAgentID,
		&i.RelatedIssueID,
		&i.RelatedRunID,
		&i.Resolution,
		&i.ResponseNote,
		&i.ResponsePayload,
		&i.ResolvedByUserID,
		&i.ResolvedAt,
		&i.AcknowledgedByUserID,
		&i.AcknowledgedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const countInboxItemsBySquad = `-- name: CountInboxItemsBySquad :one
SELECT count(*) FROM inbox_items
WHERE squad_id = $1
  AND ($2::inbox_category IS NULL OR category = $2)
  AND ($3::inbox_urgency IS NULL   OR urgency = $3)
  AND ($4::inbox_status IS NULL     OR status = $4)
`

type CountInboxItemsBySquadParams struct {
	SquadID        uuid.UUID         `json:"squad_id"`
	FilterCategory NullInboxCategory `json:"filter_category"`
	FilterUrgency  NullInboxUrgency  `json:"filter_urgency"`
	FilterStatus   NullInboxStatus   `json:"filter_status"`
}

func (q *Queries) CountInboxItemsBySquad(ctx context.Context, arg CountInboxItemsBySquadParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInboxItemsBySquad,
		arg.SquadID,
		arg.FilterCategory,
		arg.FilterUrgency,
		arg.FilterStatus,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnresolvedBySquad = `-- name: CountUnresolvedBySquad :one
SELECT
    COUNT(*) FILTER (WHERE status = 'pending') AS pending_count,
    COUNT(*) FILTER (WHERE status = 'acknowledged') AS acknowledged_count,
    COUNT(*) FILTER (WHERE status IN ('pending', 'acknowledged')) AS total_count
FROM inbox_items
WHERE squad_id = $1
`

type CountUnresolvedBySquadRow struct {
	PendingCount      int64 `json:"pending_count"`
	AcknowledgedCount int64 `json:"acknowledged_count"`
	TotalCount        int64 `json:"total_count"`
}

func (q *Queries) CountUnresolvedBySquad(ctx context.Context, squadID uuid.UUID) (CountUnresolvedBySquadRow, error) {
	row := q.db.QueryRowContext(ctx, countUnresolvedBySquad, squadID)
	var i CountUnresolvedBySquadRow
	err := row.Scan(&i.PendingCount, &i.AcknowledgedCount, &i.TotalCount)
	return i, err
}

const createInboxItem = `-- name: CreateInboxItem :one
INSERT INTO inbox_items (
    squad_id, category, type, urgency, title, body, payload,
    requested_by_agent_id, related_agent_id, related_issue_id, related_run_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, squad_id, category, type, status, urgency, title, body, payload, requested_by_agent_id, related_agent_id, related_issue_id, related_run_id, resolution, response_note, response_payload, resolved_by_user_id, resolved_at, acknowledged_by_user_id, acknowledged_at, created_at, updated_at, expires_at
`

type CreateInboxItemParams struct {
	SquadID            uuid.UUID       `json:"squad_id"`
	Category           InboxCategory   `json:"category"`
	Type               string          `json:"type"`
	Urgency            InboxUrgency    `json:"urgency"`
	Title              string          `json:"title"`
	Body               sql.NullString  `json:"body"`
	Payload            json.RawMessage `json:"payload"`
	RequestedByAgentID uuid.NullUUID   `json:"requested_by_agent_id"`
	RelatedAgentID     uuid.NullUUID   `json:"related_agent_id"`
	RelatedIssueID     uuid.NullUUID   `json:"related_issue_id"`
	RelatedRunID       uuid.NullUUID   `json:"related_run_id"`
}

func (q *Queries) CreateInboxItem(ctx context.Context, arg CreateInboxItemParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, createInboxItem,
		arg.SquadID,
		arg.Category,
		arg.Type,
		arg.Urgency,
		arg.Title,
		arg.Body,
		arg.Payload,
		arg.RequestedByAgentID,
		arg.RelatedAgentID,
		arg.RelatedIssueID,
		arg.RelatedRunID,
	)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Category,
		&i.Type,
		&i.Status,
		&i.Urgency,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.RequestedByAgentID,
		&i.RelatedAgentID,
		&i.RelatedIssueID,
		&i.RelatedRunID,
		&i.Resolution,
		&i.ResponseNote,
		&i.ResponsePayload,
		&i.ResolvedByUserID,
		&i.ResolvedAt,
		&i.AcknowledgedByUserID,
		&i.AcknowledgedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createInboxItemOnConflictDoNothing = `-- name: CreateInboxItemOnConflictDoNothing :one
INSERT INTO inbox_items (
    squad_id, category, type, urgency, title, body, payload,
    related_agent_id, related_run_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (squad_id, related_agent_id, type) WHERE category = 'alert' AND status IN ('pending', 'acknowledged')
DO UPDATE SET updated_at = now()
RETURNING id, squad_id, category, type, status, urgency, title, body, payload, requested_by_agent_id, related_agent_id, related_issue_id, related_run_id, resolution, response_note, response_payload, resolved_by_user_id, resolved_at, acknowledged_by_user_id, acknowledged_at, created_at, updated_at, expires_at
`

type CreateInboxItemOnConflictDoNothingParams struct {
	SquadID        uuid.UUID       `json:"squad_id"`
	Category       InboxCategory   `json:"category"`
	Type           string          `json:"type"`
	Urgency        InboxUrgency    `json:"urgency"`
	Title          string          `json:"title"`
	Body           sql.NullString  `json:"body"`
	Payload        json.RawMessage `json:"payload"`
	RelatedAgentID uuid.NullUUID   `json:"related_agent_id"`
	RelatedRunID   uuid.NullUUID   `json:"related_run_id"`
}

func (q *Queries) CreateInboxItemOnConflictDoNothing(ctx context.Context, arg CreateInboxItemOnConflictDoNothingParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, createInboxItemOnConflictDoNothing,
		arg.SquadID,
		arg.Category,
		arg.Type,
		arg.Urgency,
		arg.Title,
		arg.Body,
		arg.Payload,
		arg.RelatedAgentID,
		arg.RelatedRunID,
	)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Category,
		&i.Type,
		&i.Status,
		&i.Urgency,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.RequestedByAgentID,
		&i.RelatedAgentID,
		&i.RelatedIssueID,
		&i.RelatedRunID,
		&i.Resolution,
		&i.ResponseNote,
		&i.ResponsePayload,
		&i.ResolvedByUserID,
		&i.ResolvedAt,
		&i.AcknowledgedByUserID,
		&i.AcknowledgedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createInboxItemWithExpiry = `-- name: CreateInboxItemWithExpiry :one
INSERT INTO inbox_items (
    squad_id, category, type, urgency, title, body, payload,
    requested_by_agent_id, related_agent_id, related_issue_id, related_run_id,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
    now() + make_interval(hours => $12::int)
)
RETURNING id, squad_id, category, type, status, urgency, title, body, payload, requested_by_agent_id, related_agent_id, related_issue_id, related_run_id, resolution, response_note, response_payload, resolved_by_user_id, resolved_at, acknowledged_by_user_id, acknowledged_at, created_at, updated_at, expires_at
`

type CreateInboxItemWithExpiryParams struct {
	SquadID            uuid.UUID       `json:"squad_id"`
	Category           InboxCategory   `json:"category"`
	Type               string          `json:"type"`
	Urgency            InboxUrgency    `json:"urgency"`
	Title              string          `json:"title"`
	Body               sql.NullString  `json:"body"`
	Payload            json.RawMessage `json:"payload"`
	RequestedByAgentID uuid.NullUUID   `json:"requested_by_agent_id"`
	RelatedAgentID     uuid.NullUUID   `json:"related_agent_id"`
	RelatedIssueID     uuid.NullUUID   `json:"related_issue_id"`
	RelatedRunID       uuid.NullUUID   `json:"related_run_id"`
	TimeoutHours       int32           `json:"timeout_hours"`
}

func (q *Queries) CreateInboxItemWithExpiry(ctx context.Context, arg CreateInboxItemWithExpiryParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, createInboxItemWithExpiry,
		arg.SquadID,
		arg.Category,
		arg.Type,
		arg.Urgency,
		arg.Title,
		arg.Body,
		arg.Payload,
		arg.RequestedByAgentID,
		arg.RelatedAgentID,
		arg.RelatedIssueID,
		arg.RelatedRunID,
		arg.TimeoutHours,
	)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Category,
		&i.Type,
		&i.Status,
		&i.Urgency,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.RequestedByAgentID,
		&i.RelatedAgentID,
		&i.RelatedIssueID,
		&i.RelatedRunID,
		&i.Resolution,
		&i.ResponseNote,
		&i.ResponsePayload,
		&i.ResolvedByUserID,
		&i.ResolvedAt,
		&i.AcknowledgedByUserID,
		&i.AcknowledgedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const dismissInboxItem = `-- name: DismissInboxItem :one
UPDATE inbox_items SET
    status = 'resolved',
    resolution = 'dismissed',
    resolved_by_user_id = $2,
    resolved_at = now(),
    updated_at = now()
WHERE id = $1 AND category = 'alert' AND status IN ('pending', 'acknowledged')
RETURNING id, squad_id, category, type, status, urgency, title, body, payload, requested_by_agent_id, related_agent_id, related_issue_id, related_run_id, resolution, response_note, response_payload, resolved_by_user_id, resolved_at, acknowledged_by_user_id, acknowledged_at, created_at, updated_at, expires_at
`

type DismissInboxItemParams struct {
	ID               uuid.UUID     `json:"id"`
	ResolvedByUserID uuid.NullUUID `json:"resolved_by_user_id"`
}

func (q *Queries) DismissInboxItem(ctx context.Context, arg DismissInboxItemParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, dismissInboxItem, arg.ID, arg.ResolvedByUserID)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Category,
		&i.Type,
		&i.Status,
		&i.Urgency,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.RequestedByAgentID,
		&i.RelatedAgentID,
		&i.RelatedIssueID,
		&i.RelatedRunID,
		&i.Resolution,
		&i.ResponseNote,
		&i.ResponsePayload,
		&i.ResolvedByUserID,
		&i.ResolvedAt,
		&i.AcknowledgedByUserID,
		&i.AcknowledgedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const expireInboxItem = `-- name: ExpireInboxItem :one
UPDATE inbox_items SET
    status = 'expired',
    updated_at = now()
WHERE id = $1 AND status IN ('pending', 'acknowledged')
RETURNING id, squad_id, category, type, status, urgency, title, body, payload, requested_by_agent_id, related_agent_id, related_issue_id, related_run_id, resolution, response_note, response_payload, resolved_by_user_id, resolved_at, acknowledged_by_user_id, acknowledged_at, created_at, updated_at, expires_at
`

func (q *Queries) ExpireInboxItem(ctx context.Context, id uuid.UUID) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, expireInboxItem, id)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Category,
		&i.Type,
		&i.Status,
		&i.Urgency,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.RequestedByAgentID,
		&i.RelatedAgentID,
		&i.RelatedIssueID,
		&i.RelatedRunID,
		&i.Resolution,
		&i.ResponseNote,
		&i.ResponsePayload,
		&i.ResolvedByUserID,
		&i.ResolvedAt,
		&i.AcknowledgedByUserID,
		&i.AcknowledgedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getInboxItemByID = `-- name: GetInboxItemByID :one
SELECT id, squad_id, category, type, status, urgency, title, body, payload, requested_by_agent_id, related_agent_id, related_issue_id, related_run_id, resolution, response_note, response_payload, resolved_by_user_id, resolved_at, acknowledged_by_user_id, acknowledged_at, created_at, updated_at, expires_at FROM inbox_items WHERE id = $1
`

func (q *Queries) GetInboxItemByID(ctx context.Context, id uuid.UUID) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, getInboxItemByID, id)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Category,
		&i.Type,
		&i.Status,
		&i.Urgency,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.RequestedByAgentID,
		&i.RelatedAgentID,
		&i.RelatedIssueID,
		&i.RelatedRunID,
		&i.Resolution,
		&i.ResponseNote,
		&i.ResponsePayload,
		&i.ResolvedByUserID,
		&i.ResolvedAt,
		&i.AcknowledgedByUserID,
		&i.AcknowledgedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listExpiredApprovalItems = `-- name: ListExpiredApprovalItems :many
SELECT id, squad_id, category, type, status, urgency, title, body, payload, requested_by_agent_id, related_agent_id, related_issue_id, related_run_id, resolution, response_note, response_payload, resolved_by_user_id, resolved_at, acknowledged_by_user_id, acknowledged_at, created_at, updated_at, expires_at FROM inbox_items
WHERE category = 'approval'
  AND status IN ('pending', 'acknowledged')
  AND expires_at IS NOT NULL
  AND expires_at <= now()
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListExpiredApprovalItems(ctx context.Context, limit int32) ([]InboxItem, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredApprovalItems, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.Category,
			&i.Type,
			&i.Status,
			&i.Urgency,
			&i.Title,
			&i.Body,
			&i.Payload,
			&i.RequestedByAgentID,
			&i.RelatedAgentID,
			&i.RelatedIssueID,
			&i.RelatedRunID,
			&i.Resolution,
			&i.ResponseNote,
			&i.ResponsePayload,
			&i.ResolvedByUserID,
			&i.ResolvedAt,
			&i.AcknowledgedByUserID,
			&i.AcknowledgedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxItemsBySquad = `-- name: ListInboxItemsBySquad :many
SELECT id, squad_id, category, type, status, urgency, title, body, payload, requested_by_agent_id, related_agent_id, related_issue_id, related_run_id, resolution, response_note, response_payload, resolved_by_user_id, resolved_at, acknowledged_by_user_id, acknowledged_at, created_at, updated_at, expires_at FROM inbox_items
WHERE squad_id = $1
  AND ($2::inbox_category IS NULL OR category = $2)
  AND ($3::inbox_urgency IS NULL   OR urgency = $3)
  AND ($4::inbox_status IS NULL     OR status = $4)
ORDER BY
    CASE urgency
        WHEN 'critical' THEN 0
        WHEN 'normal' THEN 1
        WHEN 'low' THEN 2
    END,
    created_at DESC
LIMIT $6 OFFSET $5
`

type ListInboxItemsBySquadParams struct {
	SquadID        uuid.UUID         `json:"squad_id"`
	FilterCategory NullInboxCategory `json:"filter_category"`
	FilterUrgency  NullInboxUrgency  `json:"filter_urgency"`
	FilterStatus   NullInboxStatus   `json:"filter_status"`
	PageOffset     int32             `json:"page_offset"`
	PageLimit      int32             `json:"page_limit"`
}

func (q *Queries) ListInboxItemsBySquad(ctx context.Context, arg ListInboxItemsBySquadParams) ([]InboxItem, error) {
	rows, err := q.db.QueryContext(ctx, listInboxItemsBySquad,
		arg.SquadID,
		arg.FilterCategory,
		arg.FilterUrgency,
		arg.FilterStatus,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.Category,
			&i.Type,
			&i.Status,
			&i.Urgency,
			&i.Title,
			&i.Body,
			&i.Payload,
			&i.RequestedByAgentID,
			&i.RelatedAgentID,
			&i.RelatedIssueID,
			&i.RelatedRunID,
			&i.Resolution,
			&i.ResponseNote,
			&i.ResponsePayload,
			&i.ResolvedByUserID,
			&i.ResolvedAt,
			&i.AcknowledgedByUserID,
			&i.AcknowledgedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveInboxItem = `-- name: ResolveInboxItem :one
UPDATE inbox_items SET
    status = 'resolved',
    resolution = $2,
    response_note = $3,
    response_payload = $4,
    resolved_by_user_id = $5,
    resolved_at = now(),
    updated_at = now()
WHERE id = $1 AND status IN ('pending', 'acknowledged')
RETURNING id, squad_id, category, type, status, urgency, title, body, payload, requested_by_agent_id, related_agent_id, related_issue_id, related_run_id, resolution, response_note, response_payload, resolved_by_user_id, resolved_at, acknowledged_by_user_id, acknowledged_at, created_at, updated_at, expires_at
`

type ResolveInboxItemParams struct {
	ID               uuid.UUID             `json:"id"`
	Resolution       NullInboxResolution   `json:"resolution"`
	ResponseNote     sql.NullString        `json:"response_note"`
	ResponsePayload  pqtype.NullRawMessage `json:"response_payload"`
	ResolvedByUserID uuid.NullUUID         `json:"resolved_by_user_id"`
}

func (q *Queries) ResolveInboxItem(ctx context.Context, arg ResolveInboxItemParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, resolveInboxItem,
		arg.ID,
		arg.Resolution,
		arg.ResponseNote,
		arg.ResponsePayload,
		arg.ResolvedByUserID,
	)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Category,
		&i.Type,
		&i.Status,
		&i.Urgency,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.RequestedByAgentID,
		&i.RelatedAgentID,
		&i.RelatedIssueID,
		&i.RelatedRunID,
		&i.Resolution,
		&i.ResponseNote,
		&i.ResponsePayload,
		&i.ResolvedByUserID,
		&i.ResolvedAt,
		&i.AcknowledgedByUserID,
		&i.AcknowledgedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
