// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countIssuesBySquad = `-- name: CountIssuesBySquad :one
SELECT count(*) FROM issues
WHERE squad_id = $1
  AND ($2::issue_status IS NULL           OR status = $2)
  AND ($3::issue_priority IS NULL       OR priority = $3)
  AND ($4::issue_type IS NULL               OR type = $4)
  AND ($5::UUID IS NULL        OR assignee_agent_id = $5)
  AND ($6::UUID IS NULL         OR assignee_user_id = $6)
  AND ($7::UUID IS NULL               OR project_id = $7)
  AND ($8::UUID IS NULL                  OR goal_id = $8)
  AND ($9::UUID IS NULL                OR parent_id = $9)
`

type CountIssuesBySquadParams struct {
	SquadID               uuid.UUID         `json:"squad_id"`
	FilterStatus          NullIssueStatus   `json:"filter_status"`
	FilterPriority        NullIssuePriority `json:"filter_priority"`
	FilterType            NullIssueType     `json:"filter_type"`
	FilterAssigneeAgentID uuid.NullUUID     `json:"filter_assignee_agent_id"`
	FilterAssigneeUserID  uuid.NullUUID     `json:"filter_assignee_user_id"`
	FilterProjectID       uuid.NullUUID     `json:"filter_project_id"`
	FilterGoalID          uuid.NullUUID     `json:"filter_goal_id"`
	FilterParentID        uuid.NullUUID     `json:"filter_parent_id"`
}

func (q *Queries) CountIssuesBySquad(ctx context.Context, arg CountIssuesBySquadParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIssuesBySquad,
		arg.SquadID,
		arg.FilterStatus,
		arg.FilterPriority,
		arg.FilterType,
		arg.FilterAssigneeAgentID,
		arg.FilterAssigneeUserID,
		arg.FilterProjectID,
		arg.FilterGoalID,
		arg.FilterParentID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubTasks = `-- name: CountSubTasks :one
SELECT count(*) FROM issues WHERE parent_id = $1
`

func (q *Queries) CountSubTasks(ctx context.Context, parentID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubTasks, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIssue = `-- name: CreateIssue :one
INSERT INTO issues (
    squad_id, identifier, type, title, description, status, priority,
    parent_id, project_id, goal_id, assignee_agent_id, assignee_user_id,
    billing_code, request_depth
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14
)
RETURNING id, squad_id, identifier, type, title, description, status, priority, parent_id, project_id, goal_id, assignee_agent_id, assignee_user_id, billing_code, request_depth, created_at, updated_at
`

type CreateIssueParams struct {
	SquadID         uuid.UUID      `json:"squad_id"`
	Identifier      string         `json:"identifier"`
	Type            IssueType      `json:"type"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	Status          IssueStatus    `json:"status"`
	Priority        IssuePriority  `json:"priority"`
	ParentID        uuid.NullUUID  `json:"parent_id"`
	ProjectID       uuid.NullUUID  `json:"project_id"`
	GoalID          uuid.NullUUID  `json:"goal_id"`
	AssigneeAgentID uuid.NullUUID  `json:"assignee_agent_id"`
	AssigneeUserID  uuid.NullUUID  `json:"assignee_user_id"`
	BillingCode     sql.NullString `json:"billing_code"`
	RequestDepth    int32          `json:"request_depth"`
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, createIssue,
		arg.SquadID,
		arg.Identifier,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.ParentID,
		arg.ProjectID,
		arg.GoalID,
		arg.AssigneeAgentID,
		arg.AssigneeUserID,
		arg.BillingCode,
		arg.RequestDepth,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Identifier,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ParentID,
		&i.ProjectID,
		&i.GoalID,
		&i.AssigneeAgentID,
		&i.AssigneeUserID,
		&i.BillingCode,
		&i.RequestDepth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIssue = `-- name: DeleteIssue :exec
DELETE FROM issues WHERE id = $1
`

func (q *Queries) DeleteIssue(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteIssue, id)
	return err
}

const getIssueByID = `-- name: GetIssueByID :one
SELECT id, squad_id, identifier, type, title, description, status, priority, parent_id, project_id, goal_id, assignee_agent_id, assignee_user_id, billing_code, request_depth, created_at, updated_at FROM issues WHERE id = $1
`

func (q *Queries) GetIssueByID(ctx context.Context, id uuid.UUID) (Issue, error) {
	row := q.db.QueryRowContext(ctx, getIssueByID, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Identifier,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ParentID,
		&i.ProjectID,
		&i.GoalID,
		&i.AssigneeAgentID,
		&i.AssigneeUserID,
		&i.BillingCode,
		&i.RequestDepth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssueByIdentifier = `-- name: GetIssueByIdentifier :one
SELECT id, squad_id, identifier, type, title, description, status, priority, parent_id, project_id, goal_id, assignee_agent_id, assignee_user_id, billing_code, request_depth, created_at, updated_at FROM issues WHERE squad_id = $1 AND identifier = $2
`

type GetIssueByIdentifierParams struct {
	SquadID    uuid.UUID `json:"squad_id"`
	Identifier string    `json:"identifier"`
}

func (q *Queries) GetIssueByIdentifier(ctx context.Context, arg GetIssueByIdentifierParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, getIssueByIdentifier, arg.SquadID, arg.Identifier)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Identifier,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ParentID,
		&i.ProjectID,
		&i.GoalID,
		&i.AssigneeAgentID,
		&i.AssigneeUserID,
		&i.BillingCode,
		&i.RequestDepth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementSquadIssueCounter = `-- name: IncrementSquadIssueCounter :one
UPDATE squads
SET issue_counter = issue_counter + 1,
    updated_at = now()
WHERE id = $1
RETURNING issue_prefix, issue_counter
`

type IncrementSquadIssueCounterRow struct {
	IssuePrefix  string `json:"issue_prefix"`
	IssueCounter int64  `json:"issue_counter"`
}

func (q *Queries) IncrementSquadIssueCounter(ctx context.Context, id uuid.UUID) (IncrementSquadIssueCounterRow, error) {
	row := q.db.QueryRowContext(ctx, incrementSquadIssueCounter, id)
	var i IncrementSquadIssueCounterRow
	err := row.Scan(&i.IssuePrefix, &i.IssueCounter)
	return i, err
}

const listIssuesBySquad = `-- name: ListIssuesBySquad :many
SELECT id, squad_id, identifier, type, title, description, status, priority, parent_id, project_id, goal_id, assignee_agent_id, assignee_user_id, billing_code, request_depth, created_at, updated_at FROM issues
WHERE squad_id = $1
  AND ($2::issue_status IS NULL           OR status = $2)
  AND ($3::issue_priority IS NULL       OR priority = $3)
  AND ($4::issue_type IS NULL               OR type = $4)
  AND ($5::UUID IS NULL        OR assignee_agent_id = $5)
  AND ($6::UUID IS NULL         OR assignee_user_id = $6)
  AND ($7::UUID IS NULL               OR project_id = $7)
  AND ($8::UUID IS NULL                  OR goal_id = $8)
  AND ($9::UUID IS NULL                OR parent_id = $9)
ORDER BY
    CASE WHEN $10::TEXT = 'created_at'  THEN created_at END DESC,
    CASE WHEN $10::TEXT = 'updated_at'  THEN updated_at END DESC,
    CASE WHEN $10::TEXT = 'priority'    THEN priority   END ASC,
    CASE WHEN $10::TEXT = 'status'      THEN status     END ASC,
    created_at DESC
LIMIT  $12
OFFSET $11
`

type ListIssuesBySquadParams struct {
	SquadID               uuid.UUID         `json:"squad_id"`
	FilterStatus          NullIssueStatus   `json:"filter_status"`
	FilterPriority        NullIssuePriority `json:"filter_priority"`
	FilterType            NullIssueType     `json:"filter_type"`
	FilterAssigneeAgentID uuid.NullUUID     `json:"filter_assignee_agent_id"`
	FilterAssigneeUserID  uuid.NullUUID     `json:"filter_assignee_user_id"`
	FilterProjectID       uuid.NullUUID     `json:"filter_project_id"`
	FilterGoalID          uuid.NullUUID     `json:"filter_goal_id"`
	FilterParentID        uuid.NullUUID     `json:"filter_parent_id"`
	SortField             string            `json:"sort_field"`
	PageOffset            int32             `json:"page_offset"`
	PageLimit             int32             `json:"page_limit"`
}

func (q *Queries) ListIssuesBySquad(ctx context.Context, arg ListIssuesBySquadParams) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, listIssuesBySquad,
		arg.SquadID,
		arg.FilterStatus,
		arg.FilterPriority,
		arg.FilterType,
		arg.FilterAssigneeAgentID,
		arg.FilterAssigneeUserID,
		arg.FilterProjectID,
		arg.FilterGoalID,
		arg.FilterParentID,
		arg.SortField,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.Identifier,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.ParentID,
			&i.ProjectID,
			&i.GoalID,
			&i.AssigneeAgentID,
			&i.AssigneeUserID,
			&i.BillingCode,
			&i.RequestDepth,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssue = `-- name: UpdateIssue :one
UPDATE issues
SET
    title             = COALESCE($1, title),
    description       = CASE WHEN $2::boolean THEN $3 ELSE description END,
    type              = COALESCE($4, type),
    status            = COALESCE($5, status),
    priority          = COALESCE($6, priority),
    parent_id         = CASE WHEN $7::boolean THEN $8 ELSE parent_id END,
    project_id        = CASE WHEN $9::boolean THEN $10 ELSE project_id END,
    goal_id           = CASE WHEN $11::boolean THEN $12 ELSE goal_id END,
    assignee_agent_id = CASE WHEN $13::boolean THEN $14 ELSE assignee_agent_id END,
    assignee_user_id  = CASE WHEN $15::boolean THEN $16 ELSE assignee_user_id END,
    billing_code      = CASE WHEN $17::boolean THEN $18 ELSE billing_code END
WHERE id = $19
RETURNING id, squad_id, identifier, type, title, description, status, priority, parent_id, project_id, goal_id, assignee_agent_id, assignee_user_id, billing_code, request_depth, created_at, updated_at
`

type UpdateIssueParams struct {
	Title            sql.NullString    `json:"title"`
	SetDescription   bool              `json:"set_description"`
	Description      sql.NullString    `json:"description"`
	Type             NullIssueType     `json:"type"`
	Status           NullIssueStatus   `json:"status"`
	Priority         NullIssuePriority `json:"priority"`
	SetParent        bool              `json:"set_parent"`
	ParentID         uuid.NullUUID     `json:"parent_id"`
	SetProject       bool              `json:"set_project"`
	ProjectID        uuid.NullUUID     `json:"project_id"`
	SetGoal          bool              `json:"set_goal"`
	GoalID           uuid.NullUUID     `json:"goal_id"`
	SetAssigneeAgent bool              `json:"set_assignee_agent"`
	AssigneeAgentID  uuid.NullUUID     `json:"assignee_agent_id"`
	SetAssigneeUser  bool              `json:"set_assignee_user"`
	AssigneeUserID   uuid.NullUUID     `json:"assignee_user_id"`
	SetBillingCode   bool              `json:"set_billing_code"`
	BillingCode      sql.NullString    `json:"billing_code"`
	ID               uuid.UUID         `json:"id"`
}

func (q *Queries) UpdateIssue(ctx context.Context, arg UpdateIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, updateIssue,
		arg.Title,
		arg.SetDescription,
		arg.Description,
		arg.Type,
		arg.Status,
		arg.Priority,
		arg.SetParent,
		arg.ParentID,
		arg.SetProject,
		arg.ProjectID,
		arg.SetGoal,
		arg.GoalID,
		arg.SetAssigneeAgent,
		arg.AssigneeAgentID,
		arg.SetAssigneeUser,
		arg.AssigneeUserID,
		arg.SetBillingCode,
		arg.BillingCode,
		arg.ID,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Identifier,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ParentID,
		&i.ProjectID,
		&i.GoalID,
		&i.AssigneeAgentID,
		&i.AssigneeUserID,
		&i.BillingCode,
		&i.RequestDepth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
