// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issue_comments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countIssueComments = `-- name: CountIssueComments :one
SELECT count(*) FROM issue_comments WHERE issue_id = $1
`

func (q *Queries) CountIssueComments(ctx context.Context, issueID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIssueComments, issueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIssueComment = `-- name: CreateIssueComment :one
INSERT INTO issue_comments (issue_id, author_type, author_id, body)
VALUES ($1, $2, $3, $4)
RETURNING id, issue_id, author_type, author_id, body, created_at, updated_at
`

type CreateIssueCommentParams struct {
	IssueID    uuid.UUID         `json:"issue_id"`
	AuthorType CommentAuthorType `json:"author_type"`
	AuthorID   uuid.UUID         `json:"author_id"`
	Body       string            `json:"body"`
}

func (q *Queries) CreateIssueComment(ctx context.Context, arg CreateIssueCommentParams) (IssueComment, error) {
	row := q.db.QueryRowContext(ctx, createIssueComment,
		arg.IssueID,
		arg.AuthorType,
		arg.AuthorID,
		arg.Body,
	)
	var i IssueComment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AuthorType,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIssueComments = `-- name: ListIssueComments :many
SELECT id, issue_id, author_type, author_id, body, created_at, updated_at FROM issue_comments
WHERE issue_id = $1
ORDER BY created_at ASC
LIMIT  $3
OFFSET $2
`

type ListIssueCommentsParams struct {
	IssueID    uuid.UUID `json:"issue_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

func (q *Queries) ListIssueComments(ctx context.Context, arg ListIssueCommentsParams) ([]IssueComment, error) {
	rows, err := q.db.QueryContext(ctx, listIssueComments, arg.IssueID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueComment{}
	for rows.Next() {
		var i IssueComment
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.AuthorType,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
