// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AdapterType string

const (
	AdapterTypeClaudeLocal     AdapterType = "claude_local"
	AdapterTypeCodexLocal      AdapterType = "codex_local"
	AdapterTypeCursor          AdapterType = "cursor"
	AdapterTypeProcess         AdapterType = "process"
	AdapterTypeHttp            AdapterType = "http"
	AdapterTypeOpenclawGateway AdapterType = "openclaw_gateway"
)

func (e *AdapterType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdapterType(s)
	case string:
		*e = AdapterType(s)
	default:
		return fmt.Errorf("unsupported scan type for AdapterType: %T", src)
	}
	return nil
}

type NullAdapterType struct {
	AdapterType AdapterType `json:"adapter_type"`
	Valid       bool        `json:"valid"` // Valid is true if AdapterType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdapterType) Scan(value interface{}) error {
	if value == nil {
		ns.AdapterType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdapterType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdapterType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdapterType), nil
}

type AgentRole string

const (
	AgentRoleCaptain AgentRole = "captain"
	AgentRoleLead    AgentRole = "lead"
	AgentRoleMember  AgentRole = "member"
)

func (e *AgentRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentRole(s)
	case string:
		*e = AgentRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentRole: %T", src)
	}
	return nil
}

type NullAgentRole struct {
	AgentRole AgentRole `json:"agent_role"`
	Valid     bool      `json:"valid"` // Valid is true if AgentRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentRole) Scan(value interface{}) error {
	if value == nil {
		ns.AgentRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentRole), nil
}

type AgentStatus string

const (
	AgentStatusPendingApproval AgentStatus = "pending_approval"
	AgentStatusActive          AgentStatus = "active"
	AgentStatusIdle            AgentStatus = "idle"
	AgentStatusRunning         AgentStatus = "running"
	AgentStatusError           AgentStatus = "error"
	AgentStatusPaused          AgentStatus = "paused"
	AgentStatusTerminated      AgentStatus = "terminated"
)

func (e *AgentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentStatus(s)
	case string:
		*e = AgentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentStatus: %T", src)
	}
	return nil
}

type NullAgentStatus struct {
	AgentStatus AgentStatus `json:"agent_status"`
	Valid       bool        `json:"valid"` // Valid is true if AgentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AgentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentStatus), nil
}

type CommentAuthorType string

const (
	CommentAuthorTypeAgent  CommentAuthorType = "agent"
	CommentAuthorTypeUser   CommentAuthorType = "user"
	CommentAuthorTypeSystem CommentAuthorType = "system"
)

func (e *CommentAuthorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CommentAuthorType(s)
	case string:
		*e = CommentAuthorType(s)
	default:
		return fmt.Errorf("unsupported scan type for CommentAuthorType: %T", src)
	}
	return nil
}

type NullCommentAuthorType struct {
	CommentAuthorType CommentAuthorType `json:"comment_author_type"`
	Valid             bool              `json:"valid"` // Valid is true if CommentAuthorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCommentAuthorType) Scan(value interface{}) error {
	if value == nil {
		ns.CommentAuthorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CommentAuthorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCommentAuthorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CommentAuthorType), nil
}

type IssuePriority string

const (
	IssuePriorityCritical IssuePriority = "critical"
	IssuePriorityHigh     IssuePriority = "high"
	IssuePriorityMedium   IssuePriority = "medium"
	IssuePriorityLow      IssuePriority = "low"
)

func (e *IssuePriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssuePriority(s)
	case string:
		*e = IssuePriority(s)
	default:
		return fmt.Errorf("unsupported scan type for IssuePriority: %T", src)
	}
	return nil
}

type NullIssuePriority struct {
	IssuePriority IssuePriority `json:"issue_priority"`
	Valid         bool          `json:"valid"` // Valid is true if IssuePriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssuePriority) Scan(value interface{}) error {
	if value == nil {
		ns.IssuePriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssuePriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssuePriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssuePriority), nil
}

type IssueStatus string

const (
	IssueStatusBacklog    IssueStatus = "backlog"
	IssueStatusTodo       IssueStatus = "todo"
	IssueStatusInProgress IssueStatus = "in_progress"
	IssueStatusDone       IssueStatus = "done"
	IssueStatusBlocked    IssueStatus = "blocked"
	IssueStatusCancelled  IssueStatus = "cancelled"
)

func (e *IssueStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssueStatus(s)
	case string:
		*e = IssueStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IssueStatus: %T", src)
	}
	return nil
}

type NullIssueStatus struct {
	IssueStatus IssueStatus `json:"issue_status"`
	Valid       bool        `json:"valid"` // Valid is true if IssueStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssueStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IssueStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssueStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssueStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssueStatus), nil
}

type IssueType string

const (
	IssueTypeTask         IssueType = "task"
	IssueTypeConversation IssueType = "conversation"
)

func (e *IssueType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssueType(s)
	case string:
		*e = IssueType(s)
	default:
		return fmt.Errorf("unsupported scan type for IssueType: %T", src)
	}
	return nil
}

type NullIssueType struct {
	IssueType IssueType `json:"issue_type"`
	Valid     bool      `json:"valid"` // Valid is true if IssueType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssueType) Scan(value interface{}) error {
	if value == nil {
		ns.IssueType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssueType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssueType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssueType), nil
}

type Agent struct {
	ID                 uuid.UUID             `json:"id"`
	SquadID            uuid.UUID             `json:"squad_id"`
	Name               string                `json:"name"`
	ShortName          string                `json:"short_name"`
	Role               AgentRole             `json:"role"`
	Status             AgentStatus           `json:"status"`
	ParentAgentID      uuid.NullUUID         `json:"parent_agent_id"`
	AdapterType        NullAdapterType       `json:"adapter_type"`
	AdapterConfig      pqtype.NullRawMessage `json:"adapter_config"`
	SystemPrompt       sql.NullString        `json:"system_prompt"`
	Model              sql.NullString        `json:"model"`
	BudgetMonthlyCents sql.NullInt64         `json:"budget_monthly_cents"`
	CreatedAt          time.Time             `json:"created_at"`
	UpdatedAt          time.Time             `json:"updated_at"`
}

type Goal struct {
	ID          uuid.UUID      `json:"id"`
	SquadID     uuid.UUID      `json:"squad_id"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Issue struct {
	ID              uuid.UUID      `json:"id"`
	SquadID         uuid.UUID      `json:"squad_id"`
	Identifier      string         `json:"identifier"`
	Type            IssueType      `json:"type"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	Status          IssueStatus    `json:"status"`
	Priority        IssuePriority  `json:"priority"`
	ParentID        uuid.NullUUID  `json:"parent_id"`
	ProjectID       uuid.NullUUID  `json:"project_id"`
	GoalID          uuid.NullUUID  `json:"goal_id"`
	AssigneeAgentID uuid.NullUUID  `json:"assignee_agent_id"`
	AssigneeUserID  uuid.NullUUID  `json:"assignee_user_id"`
	BillingCode     sql.NullString `json:"billing_code"`
	RequestDepth    int32          `json:"request_depth"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type IssueComment struct {
	ID         uuid.UUID         `json:"id"`
	IssueID    uuid.UUID         `json:"issue_id"`
	AuthorType CommentAuthorType `json:"author_type"`
	AuthorID   uuid.UUID         `json:"author_id"`
	Body       string            `json:"body"`
	CreatedAt  time.Time         `json:"created_at"`
	UpdatedAt  time.Time         `json:"updated_at"`
}

type Project struct {
	ID          uuid.UUID      `json:"id"`
	SquadID     uuid.UUID      `json:"squad_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Squad struct {
	ID                 uuid.UUID       `json:"id"`
	Name               string          `json:"name"`
	Slug               string          `json:"slug"`
	IssuePrefix        string          `json:"issue_prefix"`
	Description        string          `json:"description"`
	Status             string          `json:"status"`
	Settings           json.RawMessage `json:"settings"`
	IssueCounter       int64           `json:"issue_counter"`
	BudgetMonthlyCents sql.NullInt64   `json:"budget_monthly_cents"`
	BrandColor         sql.NullString  `json:"brand_color"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
}

type SquadMembership struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	SquadID   uuid.UUID `json:"squad_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"display_name"`
	PasswordHash string    `json:"-"`
	Status       string    `json:"status"`
	IsAdmin      bool      `json:"is_admin"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
