// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ActivityActorType string

const (
	ActivityActorTypeAgent  ActivityActorType = "agent"
	ActivityActorTypeUser   ActivityActorType = "user"
	ActivityActorTypeSystem ActivityActorType = "system"
)

func (e *ActivityActorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityActorType(s)
	case string:
		*e = ActivityActorType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityActorType: %T", src)
	}
	return nil
}

type NullActivityActorType struct {
	ActivityActorType ActivityActorType `json:"activity_actor_type"`
	Valid             bool              `json:"valid"` // Valid is true if ActivityActorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityActorType) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityActorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityActorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityActorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityActorType), nil
}

type AdapterType string

const (
	AdapterTypeClaudeLocal     AdapterType = "claude_local"
	AdapterTypeCodexLocal      AdapterType = "codex_local"
	AdapterTypeCursor          AdapterType = "cursor"
	AdapterTypeProcess         AdapterType = "process"
	AdapterTypeHttp            AdapterType = "http"
	AdapterTypeOpenclawGateway AdapterType = "openclaw_gateway"
)

func (e *AdapterType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdapterType(s)
	case string:
		*e = AdapterType(s)
	default:
		return fmt.Errorf("unsupported scan type for AdapterType: %T", src)
	}
	return nil
}

type NullAdapterType struct {
	AdapterType AdapterType `json:"adapter_type"`
	Valid       bool        `json:"valid"` // Valid is true if AdapterType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdapterType) Scan(value interface{}) error {
	if value == nil {
		ns.AdapterType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdapterType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdapterType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdapterType), nil
}

type AgentRole string

const (
	AgentRoleCaptain AgentRole = "captain"
	AgentRoleLead    AgentRole = "lead"
	AgentRoleMember  AgentRole = "member"
)

func (e *AgentRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentRole(s)
	case string:
		*e = AgentRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentRole: %T", src)
	}
	return nil
}

type NullAgentRole struct {
	AgentRole AgentRole `json:"agent_role"`
	Valid     bool      `json:"valid"` // Valid is true if AgentRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentRole) Scan(value interface{}) error {
	if value == nil {
		ns.AgentRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentRole), nil
}

type AgentStatus string

const (
	AgentStatusPendingApproval AgentStatus = "pending_approval"
	AgentStatusActive          AgentStatus = "active"
	AgentStatusIdle            AgentStatus = "idle"
	AgentStatusRunning         AgentStatus = "running"
	AgentStatusError           AgentStatus = "error"
	AgentStatusPaused          AgentStatus = "paused"
	AgentStatusTerminated      AgentStatus = "terminated"
)

func (e *AgentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentStatus(s)
	case string:
		*e = AgentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentStatus: %T", src)
	}
	return nil
}

type NullAgentStatus struct {
	AgentStatus AgentStatus `json:"agent_status"`
	Valid       bool        `json:"valid"` // Valid is true if AgentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AgentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentStatus), nil
}

type CommentAuthorType string

const (
	CommentAuthorTypeAgent  CommentAuthorType = "agent"
	CommentAuthorTypeUser   CommentAuthorType = "user"
	CommentAuthorTypeSystem CommentAuthorType = "system"
)

func (e *CommentAuthorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CommentAuthorType(s)
	case string:
		*e = CommentAuthorType(s)
	default:
		return fmt.Errorf("unsupported scan type for CommentAuthorType: %T", src)
	}
	return nil
}

type NullCommentAuthorType struct {
	CommentAuthorType CommentAuthorType `json:"comment_author_type"`
	Valid             bool              `json:"valid"` // Valid is true if CommentAuthorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCommentAuthorType) Scan(value interface{}) error {
	if value == nil {
		ns.CommentAuthorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CommentAuthorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCommentAuthorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CommentAuthorType), nil
}

type HeartbeatRunStatus string

const (
	HeartbeatRunStatusQueued    HeartbeatRunStatus = "queued"
	HeartbeatRunStatusRunning   HeartbeatRunStatus = "running"
	HeartbeatRunStatusSucceeded HeartbeatRunStatus = "succeeded"
	HeartbeatRunStatusFailed    HeartbeatRunStatus = "failed"
	HeartbeatRunStatusCancelled HeartbeatRunStatus = "cancelled"
	HeartbeatRunStatusTimedOut  HeartbeatRunStatus = "timed_out"
)

func (e *HeartbeatRunStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HeartbeatRunStatus(s)
	case string:
		*e = HeartbeatRunStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for HeartbeatRunStatus: %T", src)
	}
	return nil
}

type NullHeartbeatRunStatus struct {
	HeartbeatRunStatus HeartbeatRunStatus `json:"heartbeat_run_status"`
	Valid              bool               `json:"valid"` // Valid is true if HeartbeatRunStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHeartbeatRunStatus) Scan(value interface{}) error {
	if value == nil {
		ns.HeartbeatRunStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HeartbeatRunStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHeartbeatRunStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HeartbeatRunStatus), nil
}

type InboxCategory string

const (
	InboxCategoryApproval InboxCategory = "approval"
	InboxCategoryQuestion InboxCategory = "question"
	InboxCategoryDecision InboxCategory = "decision"
	InboxCategoryAlert    InboxCategory = "alert"
)

func (e *InboxCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InboxCategory(s)
	case string:
		*e = InboxCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for InboxCategory: %T", src)
	}
	return nil
}

type NullInboxCategory struct {
	InboxCategory InboxCategory `json:"inbox_category"`
	Valid         bool          `json:"valid"` // Valid is true if InboxCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInboxCategory) Scan(value interface{}) error {
	if value == nil {
		ns.InboxCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InboxCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInboxCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InboxCategory), nil
}

type InboxResolution string

const (
	InboxResolutionApproved        InboxResolution = "approved"
	InboxResolutionRejected        InboxResolution = "rejected"
	InboxResolutionRequestRevision InboxResolution = "request_revision"
	InboxResolutionAnswered        InboxResolution = "answered"
	InboxResolutionDismissed       InboxResolution = "dismissed"
)

func (e *InboxResolution) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InboxResolution(s)
	case string:
		*e = InboxResolution(s)
	default:
		return fmt.Errorf("unsupported scan type for InboxResolution: %T", src)
	}
	return nil
}

type NullInboxResolution struct {
	InboxResolution InboxResolution `json:"inbox_resolution"`
	Valid           bool            `json:"valid"` // Valid is true if InboxResolution is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInboxResolution) Scan(value interface{}) error {
	if value == nil {
		ns.InboxResolution, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InboxResolution.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInboxResolution) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InboxResolution), nil
}

type InboxStatus string

const (
	InboxStatusPending      InboxStatus = "pending"
	InboxStatusAcknowledged InboxStatus = "acknowledged"
	InboxStatusResolved     InboxStatus = "resolved"
	InboxStatusExpired      InboxStatus = "expired"
)

func (e *InboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InboxStatus(s)
	case string:
		*e = InboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InboxStatus: %T", src)
	}
	return nil
}

type NullInboxStatus struct {
	InboxStatus InboxStatus `json:"inbox_status"`
	Valid       bool        `json:"valid"` // Valid is true if InboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InboxStatus), nil
}

type InboxUrgency string

const (
	InboxUrgencyCritical InboxUrgency = "critical"
	InboxUrgencyNormal   InboxUrgency = "normal"
	InboxUrgencyLow      InboxUrgency = "low"
)

func (e *InboxUrgency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InboxUrgency(s)
	case string:
		*e = InboxUrgency(s)
	default:
		return fmt.Errorf("unsupported scan type for InboxUrgency: %T", src)
	}
	return nil
}

type NullInboxUrgency struct {
	InboxUrgency InboxUrgency `json:"inbox_urgency"`
	Valid        bool         `json:"valid"` // Valid is true if InboxUrgency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInboxUrgency) Scan(value interface{}) error {
	if value == nil {
		ns.InboxUrgency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InboxUrgency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInboxUrgency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InboxUrgency), nil
}

type IssuePriority string

const (
	IssuePriorityCritical IssuePriority = "critical"
	IssuePriorityHigh     IssuePriority = "high"
	IssuePriorityMedium   IssuePriority = "medium"
	IssuePriorityLow      IssuePriority = "low"
)

func (e *IssuePriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssuePriority(s)
	case string:
		*e = IssuePriority(s)
	default:
		return fmt.Errorf("unsupported scan type for IssuePriority: %T", src)
	}
	return nil
}

type NullIssuePriority struct {
	IssuePriority IssuePriority `json:"issue_priority"`
	Valid         bool          `json:"valid"` // Valid is true if IssuePriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssuePriority) Scan(value interface{}) error {
	if value == nil {
		ns.IssuePriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssuePriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssuePriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssuePriority), nil
}

type IssueStatus string

const (
	IssueStatusBacklog    IssueStatus = "backlog"
	IssueStatusTodo       IssueStatus = "todo"
	IssueStatusInProgress IssueStatus = "in_progress"
	IssueStatusDone       IssueStatus = "done"
	IssueStatusBlocked    IssueStatus = "blocked"
	IssueStatusCancelled  IssueStatus = "cancelled"
)

func (e *IssueStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssueStatus(s)
	case string:
		*e = IssueStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IssueStatus: %T", src)
	}
	return nil
}

type NullIssueStatus struct {
	IssueStatus IssueStatus `json:"issue_status"`
	Valid       bool        `json:"valid"` // Valid is true if IssueStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssueStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IssueStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssueStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssueStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssueStatus), nil
}

type IssueType string

const (
	IssueTypeTask         IssueType = "task"
	IssueTypeConversation IssueType = "conversation"
)

func (e *IssueType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssueType(s)
	case string:
		*e = IssueType(s)
	default:
		return fmt.Errorf("unsupported scan type for IssueType: %T", src)
	}
	return nil
}

type NullIssueType struct {
	IssueType IssueType `json:"issue_type"`
	Valid     bool      `json:"valid"` // Valid is true if IssueType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssueType) Scan(value interface{}) error {
	if value == nil {
		ns.IssueType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssueType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssueType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssueType), nil
}

type WakeupInvocationSource string

const (
	WakeupInvocationSourceOnDemand            WakeupInvocationSource = "on_demand"
	WakeupInvocationSourceTimer               WakeupInvocationSource = "timer"
	WakeupInvocationSourceAssignment          WakeupInvocationSource = "assignment"
	WakeupInvocationSourceInboxResolved       WakeupInvocationSource = "inbox_resolved"
	WakeupInvocationSourceConversationMessage WakeupInvocationSource = "conversation_message"
)

func (e *WakeupInvocationSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WakeupInvocationSource(s)
	case string:
		*e = WakeupInvocationSource(s)
	default:
		return fmt.Errorf("unsupported scan type for WakeupInvocationSource: %T", src)
	}
	return nil
}

type NullWakeupInvocationSource struct {
	WakeupInvocationSource WakeupInvocationSource `json:"wakeup_invocation_source"`
	Valid                  bool                   `json:"valid"` // Valid is true if WakeupInvocationSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWakeupInvocationSource) Scan(value interface{}) error {
	if value == nil {
		ns.WakeupInvocationSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WakeupInvocationSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWakeupInvocationSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WakeupInvocationSource), nil
}

type WakeupRequestStatus string

const (
	WakeupRequestStatusPending    WakeupRequestStatus = "pending"
	WakeupRequestStatusDispatched WakeupRequestStatus = "dispatched"
	WakeupRequestStatusDiscarded  WakeupRequestStatus = "discarded"
)

func (e *WakeupRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WakeupRequestStatus(s)
	case string:
		*e = WakeupRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WakeupRequestStatus: %T", src)
	}
	return nil
}

type NullWakeupRequestStatus struct {
	WakeupRequestStatus WakeupRequestStatus `json:"wakeup_request_status"`
	Valid               bool                `json:"valid"` // Valid is true if WakeupRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWakeupRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WakeupRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WakeupRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWakeupRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WakeupRequestStatus), nil
}

type ActivityLog struct {
	ID         uuid.UUID         `json:"id"`
	SquadID    uuid.UUID         `json:"squad_id"`
	ActorType  ActivityActorType `json:"actor_type"`
	ActorID    uuid.UUID         `json:"actor_id"`
	Action     string            `json:"action"`
	EntityType string            `json:"entity_type"`
	EntityID   uuid.UUID         `json:"entity_id"`
	Metadata   json.RawMessage   `json:"metadata"`
	CreatedAt  time.Time         `json:"created_at"`
}

type Agent struct {
	ID                 uuid.UUID             `json:"id"`
	SquadID            uuid.UUID             `json:"squad_id"`
	Name               string                `json:"name"`
	ShortName          string                `json:"short_name"`
	Role               AgentRole             `json:"role"`
	Status             AgentStatus           `json:"status"`
	ParentAgentID      uuid.NullUUID         `json:"parent_agent_id"`
	AdapterType        NullAdapterType       `json:"adapter_type"`
	AdapterConfig      pqtype.NullRawMessage `json:"adapter_config"`
	SystemPrompt       sql.NullString        `json:"system_prompt"`
	Model              sql.NullString        `json:"model"`
	BudgetMonthlyCents sql.NullInt64         `json:"budget_monthly_cents"`
	CreatedAt          time.Time             `json:"created_at"`
	UpdatedAt          time.Time             `json:"updated_at"`
}

type AgentConversationSession struct {
	ID           uuid.UUID `json:"id"`
	AgentID      uuid.UUID `json:"agent_id"`
	IssueID      uuid.UUID `json:"issue_id"`
	SessionState string    `json:"session_state"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type AgentTaskSession struct {
	ID           uuid.UUID `json:"id"`
	AgentID      uuid.UUID `json:"agent_id"`
	IssueID      uuid.UUID `json:"issue_id"`
	SessionState string    `json:"session_state"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type CostEvent struct {
	ID           uuid.UUID             `json:"id"`
	SquadID      uuid.UUID             `json:"squad_id"`
	AgentID      uuid.UUID             `json:"agent_id"`
	AmountCents  int64                 `json:"amount_cents"`
	EventType    string                `json:"event_type"`
	Model        sql.NullString        `json:"model"`
	InputTokens  sql.NullInt64         `json:"input_tokens"`
	OutputTokens sql.NullInt64         `json:"output_tokens"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	CreatedAt    time.Time             `json:"created_at"`
}

type Goal struct {
	ID          uuid.UUID      `json:"id"`
	SquadID     uuid.UUID      `json:"squad_id"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type HeartbeatRun struct {
	ID               uuid.UUID              `json:"id"`
	SquadID          uuid.UUID              `json:"squad_id"`
	AgentID          uuid.UUID              `json:"agent_id"`
	WakeupRequestID  uuid.NullUUID          `json:"wakeup_request_id"`
	InvocationSource WakeupInvocationSource `json:"invocation_source"`
	Status           HeartbeatRunStatus     `json:"status"`
	SessionIDBefore  sql.NullString         `json:"session_id_before"`
	SessionIDAfter   sql.NullString         `json:"session_id_after"`
	ExitCode         sql.NullInt32          `json:"exit_code"`
	UsageJson        pqtype.NullRawMessage  `json:"usage_json"`
	StdoutExcerpt    sql.NullString         `json:"stdout_excerpt"`
	StderrExcerpt    sql.NullString         `json:"stderr_excerpt"`
	StartedAt        sql.NullTime           `json:"started_at"`
	FinishedAt       sql.NullTime           `json:"finished_at"`
	CreatedAt        time.Time              `json:"created_at"`
}

type InboxItem struct {
	ID                   uuid.UUID             `json:"id"`
	SquadID              uuid.UUID             `json:"squad_id"`
	Category             InboxCategory         `json:"category"`
	Type                 string                `json:"type"`
	Status               InboxStatus           `json:"status"`
	Urgency              InboxUrgency          `json:"urgency"`
	Title                string                `json:"title"`
	Body                 sql.NullString        `json:"body"`
	Payload              json.RawMessage       `json:"payload"`
	RequestedByAgentID   uuid.NullUUID         `json:"requested_by_agent_id"`
	RelatedAgentID       uuid.NullUUID         `json:"related_agent_id"`
	RelatedIssueID       uuid.NullUUID         `json:"related_issue_id"`
	RelatedRunID         uuid.NullUUID         `json:"related_run_id"`
	Resolution           NullInboxResolution   `json:"resolution"`
	ResponseNote         sql.NullString        `json:"response_note"`
	ResponsePayload      pqtype.NullRawMessage `json:"response_payload"`
	ResolvedByUserID     uuid.NullUUID         `json:"resolved_by_user_id"`
	ResolvedAt           sql.NullTime          `json:"resolved_at"`
	AcknowledgedByUserID uuid.NullUUID         `json:"acknowledged_by_user_id"`
	AcknowledgedAt       sql.NullTime          `json:"acknowledged_at"`
	CreatedAt            time.Time             `json:"created_at"`
	UpdatedAt            time.Time             `json:"updated_at"`
}

type Issue struct {
	ID                uuid.UUID      `json:"id"`
	SquadID           uuid.UUID      `json:"squad_id"`
	Identifier        string         `json:"identifier"`
	Type              IssueType      `json:"type"`
	Title             string         `json:"title"`
	Description       sql.NullString `json:"description"`
	Status            IssueStatus    `json:"status"`
	Priority          IssuePriority  `json:"priority"`
	ParentID          uuid.NullUUID  `json:"parent_id"`
	ProjectID         uuid.NullUUID  `json:"project_id"`
	GoalID            uuid.NullUUID  `json:"goal_id"`
	AssigneeAgentID   uuid.NullUUID  `json:"assignee_agent_id"`
	AssigneeUserID    uuid.NullUUID  `json:"assignee_user_id"`
	BillingCode       sql.NullString `json:"billing_code"`
	RequestDepth      int32          `json:"request_depth"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	CheckoutRunID     uuid.NullUUID  `json:"checkout_run_id"`
	ExecutionLockedAt sql.NullTime   `json:"execution_locked_at"`
}

type IssueComment struct {
	ID         uuid.UUID         `json:"id"`
	IssueID    uuid.UUID         `json:"issue_id"`
	AuthorType CommentAuthorType `json:"author_type"`
	AuthorID   uuid.UUID         `json:"author_id"`
	Body       string            `json:"body"`
	CreatedAt  time.Time         `json:"created_at"`
	UpdatedAt  time.Time         `json:"updated_at"`
}

type Project struct {
	ID          uuid.UUID      `json:"id"`
	SquadID     uuid.UUID      `json:"squad_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Squad struct {
	ID                 uuid.UUID       `json:"id"`
	Name               string          `json:"name"`
	Slug               string          `json:"slug"`
	IssuePrefix        string          `json:"issue_prefix"`
	Description        string          `json:"description"`
	Status             string          `json:"status"`
	Settings           json.RawMessage `json:"settings"`
	IssueCounter       int64           `json:"issue_counter"`
	BudgetMonthlyCents sql.NullInt64   `json:"budget_monthly_cents"`
	BrandColor         sql.NullString  `json:"brand_color"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
}

type SquadMembership struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	SquadID   uuid.UUID `json:"squad_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"display_name"`
	PasswordHash string    `json:"-"`
	Status       string    `json:"status"`
	IsAdmin      bool      `json:"is_admin"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type WakeupRequest struct {
	ID               uuid.UUID              `json:"id"`
	SquadID          uuid.UUID              `json:"squad_id"`
	AgentID          uuid.UUID              `json:"agent_id"`
	InvocationSource WakeupInvocationSource `json:"invocation_source"`
	Status           WakeupRequestStatus    `json:"status"`
	ContextJson      json.RawMessage        `json:"context_json"`
	CreatedAt        time.Time              `json:"created_at"`
	DispatchedAt     sql.NullTime           `json:"dispatched_at"`
	DiscardedAt      sql.NullTime           `json:"discarded_at"`
}
