// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_connections.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOAuthConnection = `-- name: CreateOAuthConnection :one
INSERT INTO oauth_connections (user_id, provider, provider_user_id, provider_email, access_token_encrypted, refresh_token_encrypted)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, provider, provider_user_id, provider_email, access_token_encrypted, refresh_token_encrypted, created_at, updated_at
`

type CreateOAuthConnectionParams struct {
	UserID                uuid.UUID `json:"user_id"`
	Provider              string    `json:"provider"`
	ProviderUserID        string    `json:"provider_user_id"`
	ProviderEmail         string    `json:"provider_email"`
	AccessTokenEncrypted  []byte    `json:"access_token_encrypted"`
	RefreshTokenEncrypted []byte    `json:"refresh_token_encrypted"`
}

func (q *Queries) CreateOAuthConnection(ctx context.Context, arg CreateOAuthConnectionParams) (OauthConnection, error) {
	row := q.db.QueryRowContext(ctx, createOAuthConnection,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.ProviderEmail,
		arg.AccessTokenEncrypted,
		arg.RefreshTokenEncrypted,
	)
	var i OauthConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOAuthConnection = `-- name: DeleteOAuthConnection :exec
DELETE FROM oauth_connections
WHERE id = $1
`

func (q *Queries) DeleteOAuthConnection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthConnection, id)
	return err
}

const getOAuthConnectionByProviderIdentity = `-- name: GetOAuthConnectionByProviderIdentity :one
SELECT id, user_id, provider, provider_user_id, provider_email, access_token_encrypted, refresh_token_encrypted, created_at, updated_at FROM oauth_connections
WHERE provider = $1 AND provider_user_id = $2
`

type GetOAuthConnectionByProviderIdentityParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetOAuthConnectionByProviderIdentity(ctx context.Context, arg GetOAuthConnectionByProviderIdentityParams) (OauthConnection, error) {
	row := q.db.QueryRowContext(ctx, getOAuthConnectionByProviderIdentity, arg.Provider, arg.ProviderUserID)
	var i OauthConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthConnectionsByUserID = `-- name: GetOAuthConnectionsByUserID :many
SELECT id, user_id, provider, provider_user_id, provider_email, access_token_encrypted, refresh_token_encrypted, created_at, updated_at FROM oauth_connections
WHERE user_id = $1
ORDER BY provider
`

func (q *Queries) GetOAuthConnectionsByUserID(ctx context.Context, userID uuid.UUID) ([]OauthConnection, error) {
	rows, err := q.db.QueryContext(ctx, getOAuthConnectionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthConnection{}
	for rows.Next() {
		var i OauthConnection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.ProviderEmail,
			&i.AccessTokenEncrypted,
			&i.RefreshTokenEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
