// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipeline_stages.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countIssuesAtStage = `-- name: CountIssuesAtStage :one
SELECT count(*) FROM issues WHERE current_stage_id = $1
`

func (q *Queries) CountIssuesAtStage(ctx context.Context, stageID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIssuesAtStage, stageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStagesByPipeline = `-- name: CountStagesByPipeline :one
SELECT count(*) FROM pipeline_stages WHERE pipeline_id = $1
`

func (q *Queries) CountStagesByPipeline(ctx context.Context, pipelineID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStagesByPipeline, pipelineID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPipelineStage = `-- name: CreatePipelineStage :one
INSERT INTO pipeline_stages (pipeline_id, name, description, position, assigned_agent_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, pipeline_id, name, description, position, assigned_agent_id, gate_id, created_at, updated_at
`

type CreatePipelineStageParams struct {
	PipelineID      uuid.UUID      `json:"pipeline_id"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	Position        int32          `json:"position"`
	AssignedAgentID uuid.NullUUID  `json:"assigned_agent_id"`
}

func (q *Queries) CreatePipelineStage(ctx context.Context, arg CreatePipelineStageParams) (PipelineStage, error) {
	row := q.db.QueryRowContext(ctx, createPipelineStage,
		arg.PipelineID,
		arg.Name,
		arg.Description,
		arg.Position,
		arg.AssignedAgentID,
	)
	var i PipelineStage
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.AssignedAgentID,
		&i.GateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePipelineStage = `-- name: DeletePipelineStage :exec
DELETE FROM pipeline_stages WHERE id = $1
`

func (q *Queries) DeletePipelineStage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePipelineStage, id)
	return err
}

const getFirstStage = `-- name: GetFirstStage :one
SELECT id, pipeline_id, name, description, position, assigned_agent_id, gate_id, created_at, updated_at FROM pipeline_stages
WHERE pipeline_id = $1
ORDER BY position ASC
LIMIT 1
`

func (q *Queries) GetFirstStage(ctx context.Context, pipelineID uuid.UUID) (PipelineStage, error) {
	row := q.db.QueryRowContext(ctx, getFirstStage, pipelineID)
	var i PipelineStage
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.AssignedAgentID,
		&i.GateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextStage = `-- name: GetNextStage :one
SELECT id, pipeline_id, name, description, position, assigned_agent_id, gate_id, created_at, updated_at FROM pipeline_stages
WHERE pipeline_id = $1
  AND position > $2
ORDER BY position ASC
LIMIT 1
`

type GetNextStageParams struct {
	PipelineID      uuid.UUID `json:"pipeline_id"`
	CurrentPosition int32     `json:"current_position"`
}

func (q *Queries) GetNextStage(ctx context.Context, arg GetNextStageParams) (PipelineStage, error) {
	row := q.db.QueryRowContext(ctx, getNextStage, arg.PipelineID, arg.CurrentPosition)
	var i PipelineStage
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.AssignedAgentID,
		&i.GateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPipelineStageByID = `-- name: GetPipelineStageByID :one
SELECT id, pipeline_id, name, description, position, assigned_agent_id, gate_id, created_at, updated_at FROM pipeline_stages WHERE id = $1
`

func (q *Queries) GetPipelineStageByID(ctx context.Context, id uuid.UUID) (PipelineStage, error) {
	row := q.db.QueryRowContext(ctx, getPipelineStageByID, id)
	var i PipelineStage
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.AssignedAgentID,
		&i.GateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPreviousStage = `-- name: GetPreviousStage :one
SELECT id, pipeline_id, name, description, position, assigned_agent_id, gate_id, created_at, updated_at FROM pipeline_stages
WHERE pipeline_id = $1
  AND position < $2
ORDER BY position DESC
LIMIT 1
`

type GetPreviousStageParams struct {
	PipelineID      uuid.UUID `json:"pipeline_id"`
	CurrentPosition int32     `json:"current_position"`
}

func (q *Queries) GetPreviousStage(ctx context.Context, arg GetPreviousStageParams) (PipelineStage, error) {
	row := q.db.QueryRowContext(ctx, getPreviousStage, arg.PipelineID, arg.CurrentPosition)
	var i PipelineStage
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.AssignedAgentID,
		&i.GateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStagesByPipeline = `-- name: ListStagesByPipeline :many
SELECT id, pipeline_id, name, description, position, assigned_agent_id, gate_id, created_at, updated_at FROM pipeline_stages
WHERE pipeline_id = $1
ORDER BY position ASC
`

func (q *Queries) ListStagesByPipeline(ctx context.Context, pipelineID uuid.UUID) ([]PipelineStage, error) {
	rows, err := q.db.QueryContext(ctx, listStagesByPipeline, pipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineStage{}
	for rows.Next() {
		var i PipelineStage
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.Name,
			&i.Description,
			&i.Position,
			&i.AssignedAgentID,
			&i.GateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderPipelineStages = `-- name: ReorderPipelineStages :exec
UPDATE pipeline_stages
SET position = $1
WHERE id = $2 AND pipeline_id = $3
`

type ReorderPipelineStagesParams struct {
	NewPosition int32     `json:"new_position"`
	ID          uuid.UUID `json:"id"`
	PipelineID  uuid.UUID `json:"pipeline_id"`
}

func (q *Queries) ReorderPipelineStages(ctx context.Context, arg ReorderPipelineStagesParams) error {
	_, err := q.db.ExecContext(ctx, reorderPipelineStages, arg.NewPosition, arg.ID, arg.PipelineID)
	return err
}

const updatePipelineStage = `-- name: UpdatePipelineStage :one
UPDATE pipeline_stages
SET
    name              = COALESCE($1, name),
    description       = CASE WHEN $2::boolean THEN $3 ELSE description END,
    position          = COALESCE($4, position),
    assigned_agent_id = CASE WHEN $5::boolean THEN $6 ELSE assigned_agent_id END
WHERE id = $7
RETURNING id, pipeline_id, name, description, position, assigned_agent_id, gate_id, created_at, updated_at
`

type UpdatePipelineStageParams struct {
	Name            sql.NullString `json:"name"`
	SetDescription  bool           `json:"set_description"`
	Description     sql.NullString `json:"description"`
	Position        sql.NullInt32  `json:"position"`
	SetAgent        bool           `json:"set_agent"`
	AssignedAgentID uuid.NullUUID  `json:"assigned_agent_id"`
	ID              uuid.UUID      `json:"id"`
}

func (q *Queries) UpdatePipelineStage(ctx context.Context, arg UpdatePipelineStageParams) (PipelineStage, error) {
	row := q.db.QueryRowContext(ctx, updatePipelineStage,
		arg.Name,
		arg.SetDescription,
		arg.Description,
		arg.Position,
		arg.SetAgent,
		arg.AssignedAgentID,
		arg.ID,
	)
	var i PipelineStage
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.AssignedAgentID,
		&i.GateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
