// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipelines.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countIssuesInPipeline = `-- name: CountIssuesInPipeline :one
SELECT count(*) FROM issues WHERE pipeline_id = $1
`

func (q *Queries) CountIssuesInPipeline(ctx context.Context, pipelineID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIssuesInPipeline, pipelineID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPipelinesBySquad = `-- name: CountPipelinesBySquad :one
SELECT count(*) FROM pipelines
WHERE squad_id = $1
  AND ($2::boolean IS NULL OR is_active = $2)
`

type CountPipelinesBySquadParams struct {
	SquadID        uuid.UUID    `json:"squad_id"`
	FilterIsActive sql.NullBool `json:"filter_is_active"`
}

func (q *Queries) CountPipelinesBySquad(ctx context.Context, arg CountPipelinesBySquadParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPipelinesBySquad, arg.SquadID, arg.FilterIsActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPipeline = `-- name: CreatePipeline :one
INSERT INTO pipelines (squad_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, squad_id, name, description, is_active, created_at, updated_at
`

type CreatePipelineParams struct {
	SquadID     uuid.UUID      `json:"squad_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreatePipeline(ctx context.Context, arg CreatePipelineParams) (Pipeline, error) {
	row := q.db.QueryRowContext(ctx, createPipeline, arg.SquadID, arg.Name, arg.Description)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePipeline = `-- name: DeletePipeline :exec
DELETE FROM pipelines WHERE id = $1
`

func (q *Queries) DeletePipeline(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePipeline, id)
	return err
}

const getPipelineByID = `-- name: GetPipelineByID :one
SELECT id, squad_id, name, description, is_active, created_at, updated_at FROM pipelines WHERE id = $1
`

func (q *Queries) GetPipelineByID(ctx context.Context, id uuid.UUID) (Pipeline, error) {
	row := q.db.QueryRowContext(ctx, getPipelineByID, id)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPipelinesBySquad = `-- name: ListPipelinesBySquad :many
SELECT id, squad_id, name, description, is_active, created_at, updated_at FROM pipelines
WHERE squad_id = $1
  AND ($2::boolean IS NULL OR is_active = $2)
ORDER BY name ASC
LIMIT $4 OFFSET $3
`

type ListPipelinesBySquadParams struct {
	SquadID        uuid.UUID    `json:"squad_id"`
	FilterIsActive sql.NullBool `json:"filter_is_active"`
	PageOffset     int32        `json:"page_offset"`
	PageLimit      int32        `json:"page_limit"`
}

func (q *Queries) ListPipelinesBySquad(ctx context.Context, arg ListPipelinesBySquadParams) ([]Pipeline, error) {
	rows, err := q.db.QueryContext(ctx, listPipelinesBySquad,
		arg.SquadID,
		arg.FilterIsActive,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pipeline{}
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePipeline = `-- name: UpdatePipeline :one
UPDATE pipelines
SET
    name        = COALESCE($1, name),
    description = CASE WHEN $2::boolean THEN $3 ELSE description END,
    is_active   = COALESCE($4, is_active)
WHERE id = $5
RETURNING id, squad_id, name, description, is_active, created_at, updated_at
`

type UpdatePipelineParams struct {
	Name           sql.NullString `json:"name"`
	SetDescription bool           `json:"set_description"`
	Description    sql.NullString `json:"description"`
	IsActive       sql.NullBool   `json:"is_active"`
	ID             uuid.UUID      `json:"id"`
}

func (q *Queries) UpdatePipeline(ctx context.Context, arg UpdatePipelineParams) (Pipeline, error) {
	row := q.db.QueryRowContext(ctx, updatePipeline,
		arg.Name,
		arg.SetDescription,
		arg.Description,
		arg.IsActive,
		arg.ID,
	)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
