// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (squad_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, squad_id, name, description, status, created_at, updated_at
`

type CreateProjectParams struct {
	SquadID     uuid.UUID      `json:"squad_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.SquadID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, squad_id, name, description, status, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsBySquad = `-- name: ListProjectsBySquad :many
SELECT id, squad_id, name, description, status, created_at, updated_at FROM projects WHERE squad_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProjectsBySquad(ctx context.Context, squadID uuid.UUID) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsBySquad, squadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectExistsByName = `-- name: ProjectExistsByName :one
SELECT EXISTS(SELECT 1 FROM projects WHERE squad_id = $1 AND name = $2) AS exists
`

type ProjectExistsByNameParams struct {
	SquadID uuid.UUID `json:"squad_id"`
	Name    string    `json:"name"`
}

func (q *Queries) ProjectExistsByName(ctx context.Context, arg ProjectExistsByNameParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, projectExistsByName, arg.SquadID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const projectExistsByNameExcluding = `-- name: ProjectExistsByNameExcluding :one
SELECT EXISTS(SELECT 1 FROM projects WHERE squad_id = $1 AND name = $2 AND id != $3) AS exists
`

type ProjectExistsByNameExcludingParams struct {
	SquadID uuid.UUID `json:"squad_id"`
	Name    string    `json:"name"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) ProjectExistsByNameExcluding(ctx context.Context, arg ProjectExistsByNameExcludingParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, projectExistsByNameExcluding, arg.SquadID, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    name        = COALESCE($1, name),
    description = CASE WHEN $2::boolean THEN $3 ELSE description END,
    status      = COALESCE($4, status)
WHERE id = $5
RETURNING id, squad_id, name, description, status, created_at, updated_at
`

type UpdateProjectParams struct {
	Name           sql.NullString `json:"name"`
	SetDescription bool           `json:"set_description"`
	Description    sql.NullString `json:"description"`
	Status         sql.NullString `json:"status"`
	ID             uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.Name,
		arg.SetDescription,
		arg.Description,
		arg.Status,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
