// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

type Querier interface {
	// NOTE: CheckCycleInHierarchy uses a recursive CTE which sqlc cannot parse.
	// It is implemented as a raw SQL query in the repository layer. The query is:
	//
	// WITH RECURSIVE ancestors AS (
	//     SELECT id, parent_agent_id, 1 AS depth
	//     FROM agents WHERE id = $1
	//     UNION ALL
	//     SELECT a.id, a.parent_agent_id, anc.depth + 1
	//     FROM agents a JOIN ancestors anc ON a.id = anc.parent_agent_id
	//     WHERE anc.depth < 10
	// )
	// SELECT EXISTS (SELECT 1 FROM ancestors WHERE id = $2) AS would_cycle;
	CountAgentsBySquad(ctx context.Context, squadID uuid.UUID) (int64, error)
	CountGoalChildren(ctx context.Context, parentID uuid.NullUUID) (int64, error)
	CountIssueComments(ctx context.Context, issueID uuid.UUID) (int64, error)
	CountIssuesBySquad(ctx context.Context, arg CountIssuesBySquadParams) (int64, error)
	CountSquadOwners(ctx context.Context, squadID uuid.UUID) (int64, error)
	CountSubTasks(ctx context.Context, parentID uuid.NullUUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error)
	CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error)
	CreateIssueComment(ctx context.Context, arg CreateIssueCommentParams) (IssueComment, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSquad(ctx context.Context, arg CreateSquadParams) (Squad, error)
	CreateSquadMembership(ctx context.Context, arg CreateSquadMembershipParams) (SquadMembership, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteIssue(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error
	DeleteSquadMembership(ctx context.Context, arg DeleteSquadMembershipParams) error
	DeleteSquadMembershipByUserIfNotLastOwner(ctx context.Context, arg DeleteSquadMembershipByUserIfNotLastOwnerParams) (int64, error)
	DeleteSquadMembershipIfNotLastOwner(ctx context.Context, arg DeleteSquadMembershipIfNotLastOwnerParams) (int64, error)
	DemoteOwnerIfNotLast(ctx context.Context, arg DemoteOwnerIfNotLastParams) (int64, error)
	GetAgentByID(ctx context.Context, id uuid.UUID) (Agent, error)
	GetAgentParent(ctx context.Context, id uuid.UUID) (GetAgentParentRow, error)
	GetGoalAncestors(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error)
	GetGoalByID(ctx context.Context, id uuid.UUID) (Goal, error)
	GetIssueByID(ctx context.Context, id uuid.UUID) (Issue, error)
	GetIssueByIdentifier(ctx context.Context, arg GetIssueByIdentifierParams) (Issue, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	GetSquadByID(ctx context.Context, id uuid.UUID) (Squad, error)
	GetSquadBySlug(ctx context.Context, slug string) (Squad, error)
	GetSquadCaptain(ctx context.Context, squadID uuid.UUID) (Agent, error)
	GetSquadMembership(ctx context.Context, arg GetSquadMembershipParams) (SquadMembership, error)
	GetSquadMembershipByID(ctx context.Context, arg GetSquadMembershipByIDParams) (SquadMembership, error)
	GetSquadSettings(ctx context.Context, id uuid.UUID) (json.RawMessage, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	IncrementIssueCounter(ctx context.Context, id uuid.UUID) (IncrementIssueCounterRow, error)
	IncrementSquadIssueCounter(ctx context.Context, id uuid.UUID) (IncrementSquadIssueCounterRow, error)
	ListAgentChildren(ctx context.Context, parentAgentID uuid.NullUUID) ([]Agent, error)
	ListAgentsBySquad(ctx context.Context, squadID uuid.UUID) ([]Agent, error)
	ListGoalsBySquad(ctx context.Context, squadID uuid.UUID) ([]Goal, error)
	ListGoalsBySquadAndParent(ctx context.Context, arg ListGoalsBySquadAndParentParams) ([]Goal, error)
	ListIssueComments(ctx context.Context, arg ListIssueCommentsParams) ([]IssueComment, error)
	ListIssuesBySquad(ctx context.Context, arg ListIssuesBySquadParams) ([]Issue, error)
	ListProjectsBySquad(ctx context.Context, squadID uuid.UUID) ([]Project, error)
	ListSquadMembers(ctx context.Context, squadID uuid.UUID) ([]ListSquadMembersRow, error)
	ListSquadMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]SquadMembership, error)
	ListSquadsByUser(ctx context.Context, arg ListSquadsByUserParams) ([]ListSquadsByUserRow, error)
	ListTopLevelGoalsBySquad(ctx context.Context, squadID uuid.UUID) ([]Goal, error)
	Ping(ctx context.Context) error
	ProjectExistsByName(ctx context.Context, arg ProjectExistsByNameParams) (bool, error)
	ProjectExistsByNameExcluding(ctx context.Context, arg ProjectExistsByNameExcludingParams) (bool, error)
	SoftDeleteSquad(ctx context.Context, id uuid.UUID) (Squad, error)
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error)
	UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error)
	UpdateIssue(ctx context.Context, arg UpdateIssueParams) (Issue, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateSquad(ctx context.Context, arg UpdateSquadParams) (Squad, error)
	UpdateSquadMembershipRole(ctx context.Context, arg UpdateSquadMembershipRoleParams) (SquadMembership, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
