// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: squad_memberships.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countSquadOwners = `-- name: CountSquadOwners :one
SELECT COUNT(*) FROM squad_memberships
WHERE squad_id = $1 AND role = 'owner'
`

func (q *Queries) CountSquadOwners(ctx context.Context, squadID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSquadOwners, squadID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSquadMembership = `-- name: CreateSquadMembership :one
INSERT INTO squad_memberships (user_id, squad_id, role)
VALUES ($1, $2, $3)
RETURNING id, user_id, squad_id, role, created_at, updated_at
`

type CreateSquadMembershipParams struct {
	UserID  uuid.UUID `json:"user_id"`
	SquadID uuid.UUID `json:"squad_id"`
	Role    string    `json:"role"`
}

func (q *Queries) CreateSquadMembership(ctx context.Context, arg CreateSquadMembershipParams) (SquadMembership, error) {
	row := q.db.QueryRowContext(ctx, createSquadMembership, arg.UserID, arg.SquadID, arg.Role)
	var i SquadMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SquadID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSquadMembership = `-- name: DeleteSquadMembership :exec
DELETE FROM squad_memberships
WHERE id = $1 AND squad_id = $2
`

type DeleteSquadMembershipParams struct {
	ID      uuid.UUID `json:"id"`
	SquadID uuid.UUID `json:"squad_id"`
}

func (q *Queries) DeleteSquadMembership(ctx context.Context, arg DeleteSquadMembershipParams) error {
	_, err := q.db.ExecContext(ctx, deleteSquadMembership, arg.ID, arg.SquadID)
	return err
}

const deleteSquadMembershipByUserIfNotLastOwner = `-- name: DeleteSquadMembershipByUserIfNotLastOwner :execrows
DELETE FROM squad_memberships sm
WHERE sm.user_id = $1 AND sm.squad_id = $2
  AND NOT (
    sm.role = 'owner'
    AND (SELECT COUNT(*) FROM squad_memberships sm2 WHERE sm2.squad_id = $2 AND sm2.role = 'owner') = 1
  )
`

type DeleteSquadMembershipByUserIfNotLastOwnerParams struct {
	UserID  uuid.UUID `json:"user_id"`
	SquadID uuid.UUID `json:"squad_id"`
}

func (q *Queries) DeleteSquadMembershipByUserIfNotLastOwner(ctx context.Context, arg DeleteSquadMembershipByUserIfNotLastOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSquadMembershipByUserIfNotLastOwner, arg.UserID, arg.SquadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSquadMembershipIfNotLastOwner = `-- name: DeleteSquadMembershipIfNotLastOwner :execrows
DELETE FROM squad_memberships sm
WHERE sm.id = $1 AND sm.squad_id = $2
  AND NOT (
    sm.role = 'owner'
    AND (SELECT COUNT(*) FROM squad_memberships sm2 WHERE sm2.squad_id = $2 AND sm2.role = 'owner') = 1
  )
`

type DeleteSquadMembershipIfNotLastOwnerParams struct {
	ID      uuid.UUID `json:"id"`
	SquadID uuid.UUID `json:"squad_id"`
}

func (q *Queries) DeleteSquadMembershipIfNotLastOwner(ctx context.Context, arg DeleteSquadMembershipIfNotLastOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSquadMembershipIfNotLastOwner, arg.ID, arg.SquadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const demoteOwnerIfNotLast = `-- name: DemoteOwnerIfNotLast :execrows
UPDATE squad_memberships sm
SET role = $1, updated_at = now()
WHERE sm.id = $2 AND sm.squad_id = $3
  AND NOT (
    sm.role = 'owner'
    AND (SELECT COUNT(*) FROM squad_memberships sm2 WHERE sm2.squad_id = $3 AND sm2.role = 'owner') = 1
  )
`

type DemoteOwnerIfNotLastParams struct {
	Role    string    `json:"role"`
	ID      uuid.UUID `json:"id"`
	SquadID uuid.UUID `json:"squad_id"`
}

func (q *Queries) DemoteOwnerIfNotLast(ctx context.Context, arg DemoteOwnerIfNotLastParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, demoteOwnerIfNotLast, arg.Role, arg.ID, arg.SquadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSquadMembership = `-- name: GetSquadMembership :one
SELECT id, user_id, squad_id, role, created_at, updated_at FROM squad_memberships
WHERE user_id = $1 AND squad_id = $2
`

type GetSquadMembershipParams struct {
	UserID  uuid.UUID `json:"user_id"`
	SquadID uuid.UUID `json:"squad_id"`
}

func (q *Queries) GetSquadMembership(ctx context.Context, arg GetSquadMembershipParams) (SquadMembership, error) {
	row := q.db.QueryRowContext(ctx, getSquadMembership, arg.UserID, arg.SquadID)
	var i SquadMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SquadID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSquadMembershipByID = `-- name: GetSquadMembershipByID :one
SELECT id, user_id, squad_id, role, created_at, updated_at FROM squad_memberships
WHERE id = $1 AND squad_id = $2
`

type GetSquadMembershipByIDParams struct {
	ID      uuid.UUID `json:"id"`
	SquadID uuid.UUID `json:"squad_id"`
}

func (q *Queries) GetSquadMembershipByID(ctx context.Context, arg GetSquadMembershipByIDParams) (SquadMembership, error) {
	row := q.db.QueryRowContext(ctx, getSquadMembershipByID, arg.ID, arg.SquadID)
	var i SquadMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SquadID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSquadMembers = `-- name: ListSquadMembers :many
SELECT sm.id, sm.user_id, sm.squad_id, sm.role, sm.created_at, sm.updated_at, u.email, u.display_name
FROM squad_memberships sm
INNER JOIN users u ON u.id = sm.user_id
WHERE sm.squad_id = $1
ORDER BY sm.created_at ASC
`

type ListSquadMembersRow struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	SquadID     uuid.UUID `json:"squad_id"`
	Role        string    `json:"role"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) ListSquadMembers(ctx context.Context, squadID uuid.UUID) ([]ListSquadMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listSquadMembers, squadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSquadMembersRow{}
	for rows.Next() {
		var i ListSquadMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SquadID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSquadMembershipsByUser = `-- name: ListSquadMembershipsByUser :many
SELECT id, user_id, squad_id, role, created_at, updated_at FROM squad_memberships
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListSquadMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]SquadMembership, error) {
	rows, err := q.db.QueryContext(ctx, listSquadMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SquadMembership{}
	for rows.Next() {
		var i SquadMembership
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SquadID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSquadMembershipRole = `-- name: UpdateSquadMembershipRole :one
UPDATE squad_memberships
SET role = $1, updated_at = now()
WHERE id = $2 AND squad_id = $3
RETURNING id, user_id, squad_id, role, created_at, updated_at
`

type UpdateSquadMembershipRoleParams struct {
	Role    string    `json:"role"`
	ID      uuid.UUID `json:"id"`
	SquadID uuid.UUID `json:"squad_id"`
}

func (q *Queries) UpdateSquadMembershipRole(ctx context.Context, arg UpdateSquadMembershipRoleParams) (SquadMembership, error) {
	row := q.db.QueryRowContext(ctx, updateSquadMembershipRole, arg.Role, arg.ID, arg.SquadID)
	var i SquadMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SquadID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
