// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: squads.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createSquad = `-- name: CreateSquad :one
INSERT INTO squads (name, slug, issue_prefix, description, status, settings, budget_monthly_cents, brand_color)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, slug, issue_prefix, description, status, settings, issue_counter, budget_monthly_cents, brand_color, created_at, updated_at
`

type CreateSquadParams struct {
	Name               string          `json:"name"`
	Slug               string          `json:"slug"`
	IssuePrefix        string          `json:"issue_prefix"`
	Description        string          `json:"description"`
	Status             string          `json:"status"`
	Settings           json.RawMessage `json:"settings"`
	BudgetMonthlyCents sql.NullInt64   `json:"budget_monthly_cents"`
	BrandColor         sql.NullString  `json:"brand_color"`
}

func (q *Queries) CreateSquad(ctx context.Context, arg CreateSquadParams) (Squad, error) {
	row := q.db.QueryRowContext(ctx, createSquad,
		arg.Name,
		arg.Slug,
		arg.IssuePrefix,
		arg.Description,
		arg.Status,
		arg.Settings,
		arg.BudgetMonthlyCents,
		arg.BrandColor,
	)
	var i Squad
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IssuePrefix,
		&i.Description,
		&i.Status,
		&i.Settings,
		&i.IssueCounter,
		&i.BudgetMonthlyCents,
		&i.BrandColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSquadByID = `-- name: GetSquadByID :one
SELECT id, name, slug, issue_prefix, description, status, settings, issue_counter, budget_monthly_cents, brand_color, created_at, updated_at FROM squads WHERE id = $1
`

func (q *Queries) GetSquadByID(ctx context.Context, id uuid.UUID) (Squad, error) {
	row := q.db.QueryRowContext(ctx, getSquadByID, id)
	var i Squad
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IssuePrefix,
		&i.Description,
		&i.Status,
		&i.Settings,
		&i.IssueCounter,
		&i.BudgetMonthlyCents,
		&i.BrandColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSquadBySlug = `-- name: GetSquadBySlug :one
SELECT id, name, slug, issue_prefix, description, status, settings, issue_counter, budget_monthly_cents, brand_color, created_at, updated_at FROM squads WHERE slug = $1
`

func (q *Queries) GetSquadBySlug(ctx context.Context, slug string) (Squad, error) {
	row := q.db.QueryRowContext(ctx, getSquadBySlug, slug)
	var i Squad
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IssuePrefix,
		&i.Description,
		&i.Status,
		&i.Settings,
		&i.IssueCounter,
		&i.BudgetMonthlyCents,
		&i.BrandColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSquadSettings = `-- name: GetSquadSettings :one
SELECT settings FROM squads WHERE id = $1
`

func (q *Queries) GetSquadSettings(ctx context.Context, id uuid.UUID) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getSquadSettings, id)
	var settings json.RawMessage
	err := row.Scan(&settings)
	return settings, err
}

const incrementIssueCounter = `-- name: IncrementIssueCounter :one
UPDATE squads
SET issue_counter = issue_counter + 1, updated_at = now()
WHERE id = $1
RETURNING issue_counter, issue_prefix
`

type IncrementIssueCounterRow struct {
	IssueCounter int64  `json:"issue_counter"`
	IssuePrefix  string `json:"issue_prefix"`
}

func (q *Queries) IncrementIssueCounter(ctx context.Context, id uuid.UUID) (IncrementIssueCounterRow, error) {
	row := q.db.QueryRowContext(ctx, incrementIssueCounter, id)
	var i IncrementIssueCounterRow
	err := row.Scan(&i.IssueCounter, &i.IssuePrefix)
	return i, err
}

const listSquadsByUser = `-- name: ListSquadsByUser :many
SELECT s.id, s.name, s.slug, s.issue_prefix, s.description, s.status, s.settings, s.issue_counter, s.budget_monthly_cents, s.brand_color, s.created_at, s.updated_at, sm.role, sm.id AS membership_id
FROM squads s
INNER JOIN squad_memberships sm ON sm.squad_id = s.id
WHERE sm.user_id = $1
  AND s.status != 'archived'
ORDER BY s.name ASC
LIMIT $2 OFFSET $3
`

type ListSquadsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListSquadsByUserRow struct {
	ID                 uuid.UUID       `json:"id"`
	Name               string          `json:"name"`
	Slug               string          `json:"slug"`
	IssuePrefix        string          `json:"issue_prefix"`
	Description        string          `json:"description"`
	Status             string          `json:"status"`
	Settings           json.RawMessage `json:"settings"`
	IssueCounter       int64           `json:"issue_counter"`
	BudgetMonthlyCents sql.NullInt64   `json:"budget_monthly_cents"`
	BrandColor         sql.NullString  `json:"brand_color"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	Role               string          `json:"role"`
	MembershipID       uuid.UUID       `json:"membership_id"`
}

func (q *Queries) ListSquadsByUser(ctx context.Context, arg ListSquadsByUserParams) ([]ListSquadsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listSquadsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSquadsByUserRow{}
	for rows.Next() {
		var i ListSquadsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IssuePrefix,
			&i.Description,
			&i.Status,
			&i.Settings,
			&i.IssueCounter,
			&i.BudgetMonthlyCents,
			&i.BrandColor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.MembershipID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSquad = `-- name: SoftDeleteSquad :one
UPDATE squads
SET status = 'archived', updated_at = now()
WHERE id = $1
RETURNING id, name, slug, issue_prefix, description, status, settings, issue_counter, budget_monthly_cents, brand_color, created_at, updated_at
`

func (q *Queries) SoftDeleteSquad(ctx context.Context, id uuid.UUID) (Squad, error) {
	row := q.db.QueryRowContext(ctx, softDeleteSquad, id)
	var i Squad
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IssuePrefix,
		&i.Description,
		&i.Status,
		&i.Settings,
		&i.IssueCounter,
		&i.BudgetMonthlyCents,
		&i.BrandColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSquad = `-- name: UpdateSquad :one
UPDATE squads
SET name                 = COALESCE($1, name),
    slug                 = COALESCE($2, slug),
    description          = COALESCE($3, description),
    status               = COALESCE($4, status),
    settings             = COALESCE($5, settings),
    budget_monthly_cents = CASE
                             WHEN $6::BOOLEAN THEN $7
                             ELSE budget_monthly_cents
                           END,
    brand_color          = COALESCE($8, brand_color),
    updated_at           = now()
WHERE id = $9
RETURNING id, name, slug, issue_prefix, description, status, settings, issue_counter, budget_monthly_cents, brand_color, created_at, updated_at
`

type UpdateSquadParams struct {
	Name               sql.NullString        `json:"name"`
	Slug               sql.NullString        `json:"slug"`
	Description        sql.NullString        `json:"description"`
	Status             sql.NullString        `json:"status"`
	Settings           pqtype.NullRawMessage `json:"settings"`
	UpdateBudget       bool                  `json:"update_budget"`
	BudgetMonthlyCents sql.NullInt64         `json:"budget_monthly_cents"`
	BrandColor         sql.NullString        `json:"brand_color"`
	ID                 uuid.UUID             `json:"id"`
}

func (q *Queries) UpdateSquad(ctx context.Context, arg UpdateSquadParams) (Squad, error) {
	row := q.db.QueryRowContext(ctx, updateSquad,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Status,
		arg.Settings,
		arg.UpdateBudget,
		arg.BudgetMonthlyCents,
		arg.BrandColor,
		arg.ID,
	)
	var i Squad
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IssuePrefix,
		&i.Description,
		&i.Status,
		&i.Settings,
		&i.IssueCounter,
		&i.BudgetMonthlyCents,
		&i.BrandColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
