// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: squad_secrets.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countSquadSecrets = `-- name: CountSquadSecrets :one
SELECT count(*) FROM squad_secrets
WHERE squad_id = $1
`

func (q *Queries) CountSquadSecrets(ctx context.Context, squadID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSquadSecrets, squadID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSquadSecret = `-- name: CreateSquadSecret :one
INSERT INTO squad_secrets (squad_id, name, encrypted_value, nonce, masked_hint)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, squad_id, name, encrypted_value, nonce, masked_hint, created_at, updated_at, last_rotated_at
`

type CreateSquadSecretParams struct {
	SquadID        uuid.UUID `json:"squad_id"`
	Name           string    `json:"name"`
	EncryptedValue []byte    `json:"encrypted_value"`
	Nonce          []byte    `json:"nonce"`
	MaskedHint     string    `json:"masked_hint"`
}

func (q *Queries) CreateSquadSecret(ctx context.Context, arg CreateSquadSecretParams) (SquadSecret, error) {
	row := q.db.QueryRowContext(ctx, createSquadSecret,
		arg.SquadID,
		arg.Name,
		arg.EncryptedValue,
		arg.Nonce,
		arg.MaskedHint,
	)
	var i SquadSecret
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Name,
		&i.EncryptedValue,
		&i.Nonce,
		&i.MaskedHint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastRotatedAt,
	)
	return i, err
}

const deleteSquadSecret = `-- name: DeleteSquadSecret :exec
DELETE FROM squad_secrets
WHERE squad_id = $1 AND name = $2
`

type DeleteSquadSecretParams struct {
	SquadID uuid.UUID `json:"squad_id"`
	Name    string    `json:"name"`
}

func (q *Queries) DeleteSquadSecret(ctx context.Context, arg DeleteSquadSecretParams) error {
	_, err := q.db.ExecContext(ctx, deleteSquadSecret, arg.SquadID, arg.Name)
	return err
}

const getSquadSecretByName = `-- name: GetSquadSecretByName :one
SELECT id, squad_id, name, encrypted_value, nonce, masked_hint, created_at, updated_at, last_rotated_at FROM squad_secrets
WHERE squad_id = $1 AND name = $2
`

type GetSquadSecretByNameParams struct {
	SquadID uuid.UUID `json:"squad_id"`
	Name    string    `json:"name"`
}

func (q *Queries) GetSquadSecretByName(ctx context.Context, arg GetSquadSecretByNameParams) (SquadSecret, error) {
	row := q.db.QueryRowContext(ctx, getSquadSecretByName, arg.SquadID, arg.Name)
	var i SquadSecret
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Name,
		&i.EncryptedValue,
		&i.Nonce,
		&i.MaskedHint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastRotatedAt,
	)
	return i, err
}

const listAllSecrets = `-- name: ListAllSecrets :many
SELECT id, squad_id, name, encrypted_value, nonce, masked_hint, created_at, updated_at, last_rotated_at FROM squad_secrets
ORDER BY squad_id, name
`

func (q *Queries) ListAllSecrets(ctx context.Context) ([]SquadSecret, error) {
	rows, err := q.db.QueryContext(ctx, listAllSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SquadSecret{}
	for rows.Next() {
		var i SquadSecret
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.Name,
			&i.EncryptedValue,
			&i.Nonce,
			&i.MaskedHint,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRotatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSecretsForUpdate = `-- name: ListAllSecretsForUpdate :many
SELECT id, squad_id, name, encrypted_value, nonce, masked_hint, created_at, updated_at, last_rotated_at FROM squad_secrets
FOR UPDATE
`

func (q *Queries) ListAllSecretsForUpdate(ctx context.Context) ([]SquadSecret, error) {
	rows, err := q.db.QueryContext(ctx, listAllSecretsForUpdate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SquadSecret{}
	for rows.Next() {
		var i SquadSecret
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.Name,
			&i.EncryptedValue,
			&i.Nonce,
			&i.MaskedHint,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRotatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSquadSecrets = `-- name: ListSquadSecrets :many
SELECT id, squad_id, name, masked_hint, created_at, updated_at, last_rotated_at
FROM squad_secrets
WHERE squad_id = $1
ORDER BY name ASC
`

type ListSquadSecretsRow struct {
	ID            uuid.UUID    `json:"id"`
	SquadID       uuid.UUID    `json:"squad_id"`
	Name          string       `json:"name"`
	MaskedHint    string       `json:"masked_hint"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	LastRotatedAt sql.NullTime `json:"last_rotated_at"`
}

func (q *Queries) ListSquadSecrets(ctx context.Context, squadID uuid.UUID) ([]ListSquadSecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSquadSecrets, squadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSquadSecretsRow{}
	for rows.Next() {
		var i ListSquadSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.Name,
			&i.MaskedHint,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRotatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSquadSecretsForDecryption = `-- name: ListSquadSecretsForDecryption :many
SELECT id, squad_id, name, encrypted_value, nonce FROM squad_secrets
WHERE squad_id = $1 ORDER BY name
`

type ListSquadSecretsForDecryptionRow struct {
	ID             uuid.UUID `json:"id"`
	SquadID        uuid.UUID `json:"squad_id"`
	Name           string    `json:"name"`
	EncryptedValue []byte    `json:"encrypted_value"`
	Nonce          []byte    `json:"nonce"`
}

func (q *Queries) ListSquadSecretsForDecryption(ctx context.Context, squadID uuid.UUID) ([]ListSquadSecretsForDecryptionRow, error) {
	rows, err := q.db.QueryContext(ctx, listSquadSecretsForDecryption, squadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSquadSecretsForDecryptionRow{}
	for rows.Next() {
		var i ListSquadSecretsForDecryptionRow
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.Name,
			&i.EncryptedValue,
			&i.Nonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSquadSecretEncryption = `-- name: UpdateSquadSecretEncryption :exec
UPDATE squad_secrets
SET encrypted_value = $1,
    nonce = $2,
    last_rotated_at = now()
WHERE id = $3
`

type UpdateSquadSecretEncryptionParams struct {
	EncryptedValue []byte    `json:"encrypted_value"`
	Nonce          []byte    `json:"nonce"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) UpdateSquadSecretEncryption(ctx context.Context, arg UpdateSquadSecretEncryptionParams) error {
	_, err := q.db.ExecContext(ctx, updateSquadSecretEncryption, arg.EncryptedValue, arg.Nonce, arg.ID)
	return err
}

const updateSquadSecretValue = `-- name: UpdateSquadSecretValue :one
UPDATE squad_secrets
SET encrypted_value = $1,
    nonce = $2,
    masked_hint = $3,
    last_rotated_at = now()
WHERE squad_id = $4 AND name = $5
RETURNING id, squad_id, name, encrypted_value, nonce, masked_hint, created_at, updated_at, last_rotated_at
`

type UpdateSquadSecretValueParams struct {
	EncryptedValue []byte    `json:"encrypted_value"`
	Nonce          []byte    `json:"nonce"`
	MaskedHint     string    `json:"masked_hint"`
	SquadID        uuid.UUID `json:"squad_id"`
	Name           string    `json:"name"`
}

func (q *Queries) UpdateSquadSecretValue(ctx context.Context, arg UpdateSquadSecretValueParams) (SquadSecret, error) {
	row := q.db.QueryRowContext(ctx, updateSquadSecretValue,
		arg.EncryptedValue,
		arg.Nonce,
		arg.MaskedHint,
		arg.SquadID,
		arg.Name,
	)
	var i SquadSecret
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.Name,
		&i.EncryptedValue,
		&i.Nonce,
		&i.MaskedHint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastRotatedAt,
	)
	return i, err
}
