// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wakeup_requests.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createWakeupRequest = `-- name: CreateWakeupRequest :one
INSERT INTO wakeup_requests (squad_id, agent_id, invocation_source, context_json)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
RETURNING id, squad_id, agent_id, invocation_source, status, context_json, created_at, dispatched_at, discarded_at
`

type CreateWakeupRequestParams struct {
	SquadID          uuid.UUID              `json:"squad_id"`
	AgentID          uuid.UUID              `json:"agent_id"`
	InvocationSource WakeupInvocationSource `json:"invocation_source"`
	ContextJson      json.RawMessage        `json:"context_json"`
}

func (q *Queries) CreateWakeupRequest(ctx context.Context, arg CreateWakeupRequestParams) (WakeupRequest, error) {
	row := q.db.QueryRowContext(ctx, createWakeupRequest,
		arg.SquadID,
		arg.AgentID,
		arg.InvocationSource,
		arg.ContextJson,
	)
	var i WakeupRequest
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.AgentID,
		&i.InvocationSource,
		&i.Status,
		&i.ContextJson,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.DiscardedAt,
	)
	return i, err
}

const discardPendingWakeupsByAgent = `-- name: DiscardPendingWakeupsByAgent :exec
UPDATE wakeup_requests
SET status = 'discarded', discarded_at = now()
WHERE agent_id = $1 AND status = 'pending'
`

func (q *Queries) DiscardPendingWakeupsByAgent(ctx context.Context, agentID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, discardPendingWakeupsByAgent, agentID)
	return err
}

const getWakeupRequestByID = `-- name: GetWakeupRequestByID :one
SELECT id, squad_id, agent_id, invocation_source, status, context_json, created_at, dispatched_at, discarded_at FROM wakeup_requests WHERE id = $1
`

func (q *Queries) GetWakeupRequestByID(ctx context.Context, id uuid.UUID) (WakeupRequest, error) {
	row := q.db.QueryRowContext(ctx, getWakeupRequestByID, id)
	var i WakeupRequest
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.AgentID,
		&i.InvocationSource,
		&i.Status,
		&i.ContextJson,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.DiscardedAt,
	)
	return i, err
}

const listPendingWakeupsBySquad = `-- name: ListPendingWakeupsBySquad :many
SELECT id, squad_id, agent_id, invocation_source, status, context_json, created_at, dispatched_at, discarded_at FROM wakeup_requests
WHERE squad_id = $1 AND status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) ListPendingWakeupsBySquad(ctx context.Context, squadID uuid.UUID) ([]WakeupRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPendingWakeupsBySquad, squadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WakeupRequest{}
	for rows.Next() {
		var i WakeupRequest
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.AgentID,
			&i.InvocationSource,
			&i.Status,
			&i.ContextJson,
			&i.CreatedAt,
			&i.DispatchedAt,
			&i.DiscardedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWakeupDiscarded = `-- name: MarkWakeupDiscarded :one
UPDATE wakeup_requests
SET status = 'discarded', discarded_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, squad_id, agent_id, invocation_source, status, context_json, created_at, dispatched_at, discarded_at
`

func (q *Queries) MarkWakeupDiscarded(ctx context.Context, id uuid.UUID) (WakeupRequest, error) {
	row := q.db.QueryRowContext(ctx, markWakeupDiscarded, id)
	var i WakeupRequest
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.AgentID,
		&i.InvocationSource,
		&i.Status,
		&i.ContextJson,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.DiscardedAt,
	)
	return i, err
}

const markWakeupDispatched = `-- name: MarkWakeupDispatched :one
UPDATE wakeup_requests
SET status = 'dispatched', dispatched_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, squad_id, agent_id, invocation_source, status, context_json, created_at, dispatched_at, discarded_at
`

func (q *Queries) MarkWakeupDispatched(ctx context.Context, id uuid.UUID) (WakeupRequest, error) {
	row := q.db.QueryRowContext(ctx, markWakeupDispatched, id)
	var i WakeupRequest
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.AgentID,
		&i.InvocationSource,
		&i.Status,
		&i.ContextJson,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.DiscardedAt,
	)
	return i, err
}
