package home

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
)

// InitHomeDir creates the full directory scaffold for an Ari instance root.
// It is idempotent: existing files and directories are not overwritten.
func InitHomeDir(root string) error {
	// Create subdirectories
	dirs := []struct {
		path string
		perm os.FileMode
	}{
		{"db", 0700},
		{"logs", 0750},
		{"secrets", 0700},
		{"data", 0700},
		{"data/backups", 0700},
		{"data/storage", 0700},
		{"data/storage/runs", 0700},
		{"workspaces", 0700},
	}

	for _, d := range dirs {
		p := filepath.Join(root, d.path)
		if err := os.MkdirAll(p, d.perm); err != nil {
			return fmt.Errorf("creating directory %s: %w", d.path, err)
		}
	}

	// Generate master.key if not exists
	if err := ensureMasterKey(filepath.Join(root, "secrets", "master.key")); err != nil {
		return fmt.Errorf("ensuring master key: %w", err)
	}

	// Write default config.json if not exists
	cfgPath := filepath.Join(root, ConfigFileName)
	if _, err := os.Stat(cfgPath); os.IsNotExist(err) {
		cfg := DefaultConfig()
		cfg.Meta.Source = "ari-init"
		if err := WriteConfigFile(cfgPath, cfg); err != nil {
			return fmt.Errorf("writing default config: %w", err)
		}
	}

	// Write .env if not exists
	envPath := filepath.Join(root, ".env")
	if _, err := os.Stat(envPath); os.IsNotExist(err) {
		if err := writeEnvFile(envPath); err != nil {
			return fmt.Errorf("writing .env: %w", err)
		}
	}

	return nil
}

func ensureMasterKey(path string) error {
	if _, err := os.Stat(path); err == nil {
		return nil // already exists
	}

	key := make([]byte, 32)
	if _, err := rand.Read(key); err != nil {
		return fmt.Errorf("generating random key: %w", err)
	}

	return os.WriteFile(path, key, 0600)
}

func writeEnvFile(path string) error {
	secret := make([]byte, 32)
	if _, err := rand.Read(secret); err != nil {
		return fmt.Errorf("generating JWT secret: %w", err)
	}

	content := fmt.Sprintf("# Ari environment variables\n# Generated by ari init\nARI_JWT_SECRET=%s\n", hex.EncodeToString(secret))
	return os.WriteFile(path, []byte(content), 0600)
}
